### ISSUE TITLE
RubyKaigi 2019直前特集号

### ISSUE THREAD

**Issue by miyohide** [rubima/magazine.rubyist.net#137]
RubyKaigi 2019が2019年4月18日（木）から2019年4月20日（土）にかけて開催されます。そこでるびまでも直前特集号を作成したいと考えています。

コンテンツについては例年通り、発表者やスポンサー、その他Rubyistやそうでない方が公開したRuby Kaigi 2019に関するブログなどへのリンク集を考えています。

過去回は次のとおりです。これらの形式で掲載していきます。

- [RubyKaigi 2017直前特集号](https://magazine.rubyist.net/articles/prerubykaigi2017/preRubyKaigi2017-index.html)
- [RubyKaigi 2018直前特集号](https://magazine.rubyist.net/articles/prerubykaigi2018/preRubyKaigi2018-index.html)

ご協力いただける方は、RubyKaigi 2019直前特集号の下記ファイルに対してpull requestを送ってください。
https://github.com/rubima/magazine.rubyist.net/blob/master/articles/preRubyKaigi2019/_posts/2019-03-18-preRubyKaigi2019-index.md

Pull Requestを送るのが難しい方は、このissueに対して

- 掲載してほしいURL
- 一言コメント
- どこに掲載してほしいか（Speakerの部分か？有益情報かなど）

を記載したコメントをお送りください。

なお、更新作業は一日一回程度となり、即時対応は難しいことをご了承ください。また、Pull Requestで送られた方を優先して取り込みます。

**Comment by udzura** [comment]
こんにちは。

RubyKaigi 2019 特集号のために、「福岡のRubyコミュニティ、Rubyでないコミュニティ、そしてRubyistの私」という記事を寄稿したいのですが、この場合はマークダウンの記事をファイルごと追加してPRを出す形でよろしいでしょうか？

**Comment by miyohide** [comment]
@udzura 寄稿のお話ありがとうございます。

> この場合はマークダウンの記事をファイルごと追加してPRを出す形でよろしいでしょうか？

はい。その形でもOKです。また、ご自身のブログなどに記事を書いていただき、そこへのリンクという形を取るのもOKです。

**Comment by miyohide** [comment]
一通り更新し終わったので、Closeします。
