### ISSUE TITLE
記事の書き方の説明資料に画像を表示する方法についてを記す

### ISSUE THREAD

**Issue by miyohide** [rubima/magazine.rubyist.net#145]
https://github.com/rubima/magazine.rubyist.net/wiki/HowToNewRelease

上記に画像を表示する方法について記す。

```
画像を表示したい場合は、

`{{base}}{{site.baseurl}}/images/`をパスの先頭に付けて`![alt属性]({{base}}{{site.baseurl}}/images/画像ファイルのパス)`という形にしていただけますでしょうか。

```

**Comment by snoozer05** [comment]
READMEにある 

> - 画像へのリンクは`{{base}}{{site.baseurl}}/images/号数-記事名/ファイル名`をURLとして指定してください。

で解決されていると思われるので、こちらは閉じておきます
