### ISSUE TITLE
女性も参加しやすい（でも女性限定ではない）Ruby勉強会の記事 #tokyogirlsrb

### ISSUE THREAD

**Issue by miyohide** [rubima/magazine.rubyist.net#162]
@JunichiIto さんからTwitter経由で連絡をいただきました（https://twitter.com/jnchito/status/1090026142193467394）。

3月に開催される女性向けRuby勉強会の開催レポートをるびまに掲載希望とのこと。

次回のるびまについてはまだ未定ですが、取り急ぎ備忘録として記します。

**Comment by miyohide** [comment]
@JunichiIto 次回のるびまレポートを8/18（日）に出そうかと考えています。つきましては、8/11（日）までにレポートをいただければと考えております。スケジュールとして問題ありませんでしょうか。

**Comment by JunichiIto** [comment]
了解です。実は途中まで書きかけているのでたぶん大丈夫だと思います！
こちらから連絡できず、すいません 🙏

**Comment by JunichiIto** [comment]
@miyohide 原稿が遅れていてすいません。いちおう内部では進捗してますので、もうしばらくお待ちください。8/11までには提出しますので！

**Comment by miyohide** [comment]
@JunichiIto ご連絡ありがとうございます。了解しました。寄稿、お待ちしております。

**Comment by rlho** [comment]
@miyohide 
締切間近になってしまい大変申し訳ありません。
こちら原稿を提出させていただきたいのですがどのように内容をお渡しすれば良いでしょうか…？

他のプルリクを見ていると提出する際の形式があるようなのですが、形式についてはどこかに掲載されていますでしょうか…？
https://github.com/rubima/magazine.rubyist.net/pull/222

**Comment by neko314** [comment]
@rlho 
READMEにありますよー🙂
https://github.com/rubima/magazine.rubyist.net#%E6%9B%B8%E5%BC%8F

**Comment by rlho** [comment]
おおお！ありがとうございます！

**Comment by rlho** [comment]
@miyohide
原稿を #225でプルリク作成しております。
こちら次号掲載に間に合いますでしょうか…？
ギリギリの提出&みよひでさんのアクションがなかったため、次号掲載されるか心配してます…
何か修正点がありましたらすぐ修正するのでご確認お願いします！

**Comment by miyohide** [comment]
@rlho すみません、ちょっと動けていませんでした。掲載可能です。最後の「著者について」を書いていただけますと助かります。

**Comment by rlho** [comment]
@miyohide
お忙しいところ申し訳ありません。
著者について、8/16日中に追加します！

**Comment by rlho** [comment]
@miyohide 
著者についてを追記しました！

**Comment by miyohide** [comment]
@rlho ありがとうございます。確認しました。

**Comment by miyohide** [comment]
@JunichiIto @rlho 無事、リリースできました。寄稿ありがとうございます。
