### ISSUE TITLE
とちぎRuby会議08レポート

### ISSUE THREAD

**Issue by vestige** [rubima/magazine.rubyist.net#171]
6/29に開催がきまったので起こしておきます。
レポート担当はまだきまっていません。

**Comment by miyohide** [comment]
@vestige 了解しました。レポート担当が決まりましたらご連絡をお願いします。

**Comment by vestige** [comment]
レポート担当がきまりました。
二人でやる予定になります。連絡はこのまま自分がやる予定なのでよろしくお願いします。

@Saku35 
@tkojitu

**Comment by miyohide** [comment]
@vestige @Saku35 @tkojitu 次回のるびまレポートを8/18（日）に出そうかと考えています。つきましては、8/11（日）までにレポートをいただければと考えております。スケジュールとして問題ありませんでしょうか。

**Comment by vestige** [comment]
@miyohide りょうかいです。間に合うように調整してみますー。

**Comment by vestige** [comment]
前回と同様で申し訳ないですが、gistに書いてもらったのですが、取り込んでもらえますか？

https://gist.github.com/Saku35/627c29381716a5d5a14ffa3bf38246eb

**Comment by miyohide** [comment]
@vestige 時間もまだ先なので、pull requestとして出していただけませんでしょうか。

**Comment by vestige** [comment]
@miyohide りょうかいしました、少々お待ちください。

**Comment by miyohide** [comment]
@vestige 60号リリース予定ですので、60のところに入れてください。

**Comment by miyohide** [comment]
@vestige @Saku35 無事、リリースできました。寄稿ありがとうございます。
