### ISSUE TITLE
magazine.rubyist.netをhikiからJekyll版に移行する

### ISSUE THREAD

**Issue by miyohide** [rubima/magazine.rubyist.net#20]
ざっと作業内容を記しました。過不足あれば教えて下さい。

- [x] 57号の記事をmergeする ( #19 )
- [x] travisなどで`articles`などを変更したら`_site`を更新するように処理を書く（一旦保留）
- [x] 現状から変換ミスがないか確認する
  - [x] 変換ミスがある場合は、Pull Requestなどでご連絡ください。
- [x] 移行日を決める（4/21）
- [x] GitHub Pages もしくは Heroku に載せる
- [x] magazine.rubyist.netのDNS登録内容の変更をお願いする
  - [ ] 古いものは一時的に残す？（old-magazine.rubyist.netとか？）
- [ ] るりまにPull Requestを出す
- [x] Rubyの会のレポートURLにPull Requestを出す

**Comment by kami-zh** [comment]
Twitterの投稿を見て、なにか手伝えることがあればと思いご連絡しました！
ひとまずJekyll版を手元で動かしつつキャッチアップします。

**Comment by sho-h** [comment]
> るりまにPull Request

こちらの詳細がわかれば僕の方でPR投げるのを対応できるかもしれません！URL変更とかでしょうか？

**Comment by IsuyaKuga** [comment]
Github PagesでしたらGithubで完結してよさげですね。
私も可能でしたらぜひお手伝いさせて頂けたらなと思います。

**Comment by miyohide** [comment]
> るりまにPull Request
> 
> こちらの詳細がわかれば僕の方でPR投げるのを対応できるかもしれません！URL変更とかでしょうか？

はい。URL変更になります。

**Comment by sho-h** [comment]
>> るりまにPull Request
>>
>> こちらの詳細がわかれば僕の方でPR投げるのを対応できるかもしれません！URL変更とかでしょうか？
>>
> はい。URL変更になります。

了解です！変更内容はこちらのREADMEにありましたね。PR作成しました。

**Comment by publichtml** [comment]
Jekyll方面はさっぱりですが、たんぽぽ作業くらいならお手伝いできます 💦

**Comment by kurotaky** [comment]
Jekyll版を手元で動かしました✌️ お手伝いできるところあればやっていきます。

**Comment by znz** [comment]
変更方法まで確認できていればよかったのですが、調べる時間が取れなかったので、とりあえず意見のみになってしまってすみませんが、現状だと 0001/0001-index.html のようになっていて冗長に感じるので、 0001/index.html や 0001/ForeWord.html などになるようにすると良いのではないかと思いました。
