### ISSUE TITLE
TokyuRubyKaigi13開催レポート

### ISSUE THREAD

**Issue by igaiga** [rubima/magazine.rubyist.net#204]
- レポート担当: @igaiga 
- イベントページ https://tokyurubykaigi.github.io/tokyu13/
- 開催日: 2019年6月29日
- 書き方ページ: https://github.com/rubima/magazine.rubyist.net/wiki/HowToNewRelease
- 前回: https://github.com/rubima/magazine.rubyist.net/pull/141

今回も寄稿させていただければと思います。よろしくお願いいたします。

**Comment by miyohide** [comment]
@igaiga 次回のるびまレポートを8/18（日）に出そうかと考えています。つきましては、8/11（日）までにレポートをいただければと考えております。スケジュールとして問題ありませんでしょうか。

**Comment by igaiga** [comment]
たぶんいけると思います！がんばります！

**Comment by igaiga** [comment]
https://github.com/rubima/magazine.rubyist.net/pull/218

**Comment by miyohide** [comment]
@igaiga 無事、リリースできました。寄稿ありがとうございます。
