### ISSUE TITLE
名古屋Ruby会議04 レポート

### ISSUE THREAD

**Issue by huequica** [rubima/magazine.rubyist.net#206]
こちらのIssueを移動させたものです。
https://github.com/rubima/rubima/issues/483

**Comment by miyohide** [comment]
@huequica 次回のるびまレポートを8/18（日）に出そうかと考えています。つきましては、8/11（日）までにレポートをいただければと考えております。スケジュールとして問題ありませんでしょうか。

**Comment by huequica** [comment]
遅れましてすいません、その日付で大丈夫です。  
ちなみに仮の原稿自体は出来てるので画像のみ後乗せでよければPR出せますが、どうしましょう

**Comment by miyohide** [comment]
@huequica 画像込みでPull Requestを出してください。

**Comment by huequica** [comment]
了解です。ファイル名はどうしますか？

**Comment by miyohide** [comment]
@huequica `articles/0060/_posts/2019-08-18-0060-NagoyaRubyKaigi04Report.md`でお願いします。

**Comment by miyohide** [comment]
@huequica 無事、リリースできました。寄稿ありがとうございます。
