### ISSUE TITLE
Rails Girls Nagano 1stの開催レポート

### ISSUE THREAD

**Issue by emorima** [rubima/magazine.rubyist.net#207]
- レポート担当: @cobachie
- イベントページ http://railsgirls.com/nagano

https://github.com/rubima/rubima/issues/484

**Comment by miyohide** [comment]
@emorima @cobachie 次回のるびまレポートを8/18（日）に出そうかと考えています。つきましては、8/11（日）までにレポートをいただければと考えております。スケジュールとして問題ありませんでしょうか。

**Comment by cobachie** [comment]
承知しました！ 💪 
よろしくおねがいします！

**Comment by miyohide** [comment]
@emorima @cobachie 無事、リリースできました。寄稿ありがとうございます。
