### ISSUE TITLE
Yokohama.rb 第100回レポート

### ISSUE THREAD

**Issue by publichtml** [rubima/magazine.rubyist.net#211]
- レポート担当: @publichtml 
- イベントページ https://yokohamarb.doorkeeper.jp/events/87100
- 開催日: 2019年3月16日

他のissueで次号は8/18(日)リリース、締切は8/11(日)までと拝見しましたが、こちらも次の号に含めることは可能でしょうか？
スケジュール的には、締切までだいぶ余裕をもって提出できそうです。

**Comment by miyohide** [comment]
@publichtml 寄稿のお話しありがとうございます。次の号に含めることは可能です。

**Comment by publichtml** [comment]
ありがとうございます。では近々PRを出します。

**Comment by miyohide** [comment]
@publichtml 無事、リリースできました。寄稿ありがとうございます。
