### ISSUE TITLE
Tama Ruby会議01レポート

### ISSUE THREAD

**Issue by Shigeyuki-fukuda** [rubima/magazine.rubyist.net#213]
はじめまして、こちらでは初めてissue作成させて頂きます。
Tama.rbを運営しております福田と申します。

issueの作成が遅くなり申し訳ありません 🙏 
先日、掲題のイベントを開催致しました。
レポート担当など決定事項を共有させて頂きます。

## 詳細
- レポート担当
@neko314 
- イベントページ
https://tama-rb.github.io/tamarubykaigi01/
- 開催日時
2019年7月6日13:00~18:20

**Comment by miyohide** [comment]
@Shigeyuki-fukuda @neko314 ご連絡ありがとうございます。

次回のるびまレポートを8/18（日）に出そうかと考えています。つきましては、8/11（日）までにレポートをいただければと考えております。スケジュール上問題ありませんでしょうか。

難しいようであれば、次々号への掲載となります。

**Comment by neko314** [comment]
@miyohide 

スケジュール、問題ないです。
可能な限り早く仕上げたいと思っています。
よろしくお願いいたします。

**Comment by Shigeyuki-fukuda** [comment]
@miyohide 

>@miyohide
スケジュール、問題ないです。
可能な限り早く仕上げたいと思っています。
よろしくお願いいたします。

とのことですので、宜しくお願い致します 🙇 

@neko314 
お手数おかけしますが、宜しくお願い致します 🙏

**Comment by miyohide** [comment]
@neko314 @Shigeyuki-fukuda 無事、リリースできました。寄稿ありがとうございます。
