### ISSUE TITLE
Rails Girls Sendai 2ndの開催レポート

### ISSUE THREAD

**Issue by emorima** [rubima/magazine.rubyist.net#215]
@miyohide Rails Girls Sendai 2ndの開催レポートを書きます!

- レポート担当: @HalucaAya
- イベントページ http://railsgirls.com/sendai

記事の書き方については、以下にまとめられているとのこと。
https://github.com/rubima/magazine.rubyist.net/wiki/HowToNewRelease

次回のるびまレポートは、8/18（日）の予定。
8/11（日）までにレポートを提出する。

**Comment by miyohide** [comment]
@emorima @HalucaAya 無事、リリースできました。寄稿ありがとうございます。
