### ISSUE TITLE
Rubyist Hotlinks 【第 8 回】インタビュー本文のリンク切れ？

### ISSUE THREAD

**Issue by neko314** [rubima/magazine.rubyist.net#248]
[Rubyist Hotlinks 【第 8 回】 田中哲さん](https://magazine.rubyist.net/articles/0008/0008-Hotlinks.html)のインタビュー本文が数ページに分かれているという記載がありますが、そのリンクが本文に飛ばないようです。

自分で修正PRまでできないかという検証ができていないのですが、急ぎissue立てさせていただきます。

**Comment by miyohide** [comment]
#249 にて修正済み。
