### ISSUE TITLE
大阪Ruby会議02の開催レポート

### ISSUE THREAD

**Issue by Islands5** [rubima/magazine.rubyist.net#251]
はじめまして、こちらで初めてissue作成させて頂きます。
naniwa.rbの運営メンバーをさせていただいております五島と申します。
よろしくおねがいします。

先月、掲題のイベントを開催致しましたので報告させていただきます

## 詳細
* レポート担当
  @Islands5
* イベントページ
  http://regional.rubykaigi.org/osaka02/
* 開催日時
  2019年9月15日(日) 9時〜17時

レポートの制作を少しずつ進めております
61号のリリース予定日がお決まりでしたらご教授頂きたいです
お手数おかけしますが、よろしくお願い致します

**Comment by miyohide** [comment]
@Islands5 ご連絡ありがとうございます。るびま編集担当者の miyohide と申します。

61号のリリース予定日ですが具体的には決まっていません。早くて2019年12月末、遅くて2020年1月末ぐらいを考えていますが、何も決まっていません。

**Comment by Islands5** [comment]
@miyohide さん

> 早くて2019年12月末、遅くて2020年1月末ぐらいを考えていますが、何も決まっていません。

ご回答頂きありがとうございます!
ファイル名の変更だけで対応できるように、レポート制作だけ進めておこうと思います
ご確認頂きありがとうございました

**Comment by miyohide** [comment]
@Islands5 長い間おまたせしてすみません。次号のるびまを以下の日程で考えています。

- 2020年1月12日（日）記事締め切り
- 2020年1月26日（日）リリース

記事の準備は間に合いそうでしょうか？

**Comment by Islands5** [comment]
@miyohide 

はい!
大丈夫です!
ご連絡頂きありがとうございます!!
