### ISSUE TITLE
富山Ruby会議01 開催レポート

### ISSUE THREAD

**Issue by kunitoo** [rubima/magazine.rubyist.net#258]
Toyama.rbのkunitooです。
富山Ruby会議01の開催レポートを寄稿させていただければと思います。

- レポート担当: @noboru-i
- イベントページ: https://toyamarb.github.io/toyama-rubykaigi01/
- 開催日: 2019年11月3日(日)

よろしくお願いします。

**Comment by miyohide** [comment]
@kunitoo @noburu-i ご連絡ありがとうございます。現在のところ、次のるびまの発行を2020年1月末にリリースすることを考えています。つきましては、2020年1月初旬を目処に記事を書いていただけますと助かります。
具体的な日程感が決まりましたらまたご連絡いたします。よろしくお願いします。

**Comment by miyohide** [comment]
@kunitoo 次号のるびまを以下の日程で考えています。

- 2020年1月12日（日）記事締め切り
- 2020年1月26日（日）リリース

記事の準備は間に合いそうでしょうか？

**Comment by kunitoo** [comment]
@miyohide 日程の共有ありがとうございます。
@noboru-i スケジュール問題なさそうですか?

**Comment by noboru-i** [comment]
@miyohide @kunitoo 
連絡ありがとうございます！
記事自体はおおよそ出来ているので、リリース予定日などを設定・内容の微調整の上で、1, 2週間程度でPR出せると思います。

**Comment by miyohide** [comment]
@noboru-i @kunitoo 了解しました。ご対応、よろしくお願いします。

**Comment by noboru-i** [comment]
@miyohide 
PR出しました！
ご確認のほど、よろしくおねがいします 🙇

**Comment by miyohide** [comment]
@noboru-i @kunitoo 本日、無事リリースできました。寄稿ありがとうございました。
