### ISSUE TITLE
るびま 061号発行スケジュール

### ISSUE THREAD

**Issue by miyohide** [rubima/magazine.rubyist.net#260]
るびま 061号発行スケジュールを以下のように考えています。

- 2020年1月12日（日）記事締め切り
- 2020年1月26日（日）リリース

記事候補は

- Hotlinks
- 大阪Ruby会議02レポート #251 
- 富山Ruby会議01レポート #258 

を予定していますが、記事が明らかに足りないので他に何か有りましたらご連絡いただけますと助かります。

**Comment by kurotaky** [comment]
鹿児島Ruby会議01もレポートしたいので、担当者決まったらissue作ります！
https://k-ruby.github.io/kagoshima-rubykaigi01/

**Comment by miyohide** [comment]
@kurotaky 了解しました。ご連絡お待ちしております。
なお、上記の日程はあくまで仮です。日程変更も可能ですので難しいようでしたらその旨ご連絡ください。

**Comment by miyohide** [comment]
@kurotaky 鹿児島Ruby会議01のレポートの件、いかがでしょうか。
現状、少し締め切りをずらして

- 2020年1月26日（日）記事締め切り
- 2020年2月2日（日）リリース

を考えています。ご連絡いただけますと助かります。

**Comment by kurotaky** [comment]
@miyohide 鹿児島Ruby会議01のレポートについて、書きたいと思います!
スケジュールは https://github.com/rubima/magazine.rubyist.net/issues/260#issuecomment-571115697 で大丈夫です。一旦、自分の名前でissue立てます。

その後、他にも担当する人決まったら追記しています。

**Comment by miyohide** [comment]
@kurotaky 本日、無事リリースできました。寄稿ありがとうございました。
