### ISSUE TITLE
平成 Ruby 会議 01 開催レポート

### ISSUE THREAD

**Issue by ryamakuchi** [rubima/magazine.rubyist.net#270]
平成.rb 運営の [rry](https://twitter.com/ryamakuchi) と申します。

先月開催された、平成 Ruby 会議 01 のレポートを寄稿させていただければと思い Issue を立てました。

- レポート担当
  - @ryamakuchi
- イベントページ
  - https://heiseirb.github.io/kaigi01/
- 開催日時
  - 2019年 12月 14日（土）

よろしくお願いします！

**Comment by miyohide** [comment]
@ryamakuchi ご連絡ありがとうございます。 #260 にも記したように、次号の発行スケジュールを

- 2020年1月12日（日）記事締め切り
- 2020年1月26日（日）リリース

と考えています。この日程感でレポートの寄稿は可能でしょうか？1〜2週間ぐらいでしたらずらすことが可能ですので、上記の日程感が難しい場合でもご連絡いただけますと幸いです。

**Comment by ryamakuchi** [comment]
@miyohide 

ご連絡ありがとうございます。

https://github.com/rubima/magazine.rubyist.net/pull/272 の PR にてレポート寄稿いたしました。ご確認いただけますと幸いです！よろしくお願いします。

**Comment by miyohide** [comment]
@ryamakuchi 本日、無事リリースできました。寄稿ありがとうございました。
