### ISSUE TITLE
るびまの次回の原稿締切日について

### ISSUE THREAD

**Issue by JunichiIto** [rubima/magazine.rubyist.net#271]
@miyohide どうもこんにちは。
昨年の12月21日に開催したTokyoGirls.rb Meetup vol.2の開催レポートを次回のるびまに載せていただきたいのですが、原稿はいつまでに提出すれば良いでしょうか？
だいたいの目処が見えていたら教えてください。
よろしくお願いします。

**Comment by miyohide** [comment]
@JunichiIto ご連絡ありがとうございます。 #260 にも記したように、次号の発行スケジュールを

- 2020年1月12日（日）記事締め切り
- 2020年1月26日（日）リリース

と考えています。この日程感でレポートの寄稿は可能でしょうか？1〜2週間ぐらいでしたらずらすことが可能ですので、上記の日程感が難しい場合でもご連絡いただけますと幸いです。

**Comment by JunichiIto** [comment]
なるほど、了解です。ちょっと執筆者と相談してまた返信します！

**Comment by JunichiIto** [comment]
@miyohide 執筆者と相談したところ、「土日を1〜2回挟みたいので、1/26の提出にさせてもらえると助かる」とのことでした。
というわけで大変申し訳ないのですが、締切の調整をお願いできないでしょうか？
よろしくお願いいたします🙏

**Comment by miyohide** [comment]
@JunichiIto 了解しました。1/26提出で調整します。少々お待ち下さい。

**Comment by miyohide** [comment]
@JunichiIto 本件、以下のスケジュールはいかがでしょうか。

- 2020年1月26日（日）記事締め切り
- 2020年2月2日（日）リリース

**Comment by JunichiIto** [comment]
@miyohide はい、このスケジュールで大丈夫です！お手数おかけしてすいません。
よろしくお願いします。

**Comment by JunichiIto** [comment]
@miyohide 原稿の執筆が完了したので、ご確認よろしくお願いします 🙏 
https://github.com/rubima/magazine.rubyist.net/pull/280

@nobu09 執筆どうもありがとうございました！
