### ISSUE TITLE
鹿児島Ruby会議01レポート

### ISSUE THREAD

**Issue by kurotaky** [rubima/magazine.rubyist.net#273]
鹿児島Ruby会議01レポートを寄稿します。

レポート担当: K-Rubyのメンバー + @kurotaky
イベントページ: https://k-ruby.github.io/kagoshima-rubykaigi01/
開催日: 2019年11月30日(土)

### リリースまでのスケジュール
* 2020年1月26日（日）記事締め切り
* 2020年2月2日（日）リリース

https://github.com/rubima/magazine.rubyist.net/issues/260

**Comment by miyohide** [comment]
@kurotaky 本日、無事リリースできました。寄稿ありがとうございました。
