### ISSUE TITLE
Do you have a plan to make it international ?

### ISSUE THREAD

**Issue by MarcSteven** [rubima/magazine.rubyist.net#286]
I think it's a great magazine, but it's only Japanese, so for more Ruby developers it's tough to read because of the limited language, so is it possible to make it international, for instance it supports more languages -English and so on

**Comment by miyohide** [comment]
Thank you for your feedback.

Currently, there is no plan to make an international version such as English. The reasons are as follows.

- Many people who write articles are native speakers of Japanese, and it is difficult to write articles in English.
- Nobody translates articles from Japanese to other languages, such as English.

**Comment by MarcSteven** [comment]
@miyohide Yeah right, I know it's not easy, but I think sharing is a good way to spread culture about programming language. So I think English is not a hardship for the authors.

**Comment by MarcSteven** [comment]
Okay, now close the issue, when you are ready to make it happen, please add this into the milestone. Thank u so much.
