### ISSUE TITLE
記事生成不調 (#0023 RSpec)

### ISSUE THREAD

**Issue by topstone** [rubima/magazine.rubyist.net#294]
「[スはスペックのス 【第 2 回】 RSpec on Rails (コントローラとビュー編)](https://magazine.rubyist.net/articles/0023/0023-Rspec.html)」が正しく生成されていないようで、最後の方の表示がおかしいです。

debug して Pull Request まで上げたかったのですが、時間がないので issue 報告だけしておきます。

**Comment by miyohide** [comment]
@topstone ご指摘ありがとうございます。 #295 にて修正対応します。
