### ISSUE TITLE
Kaigi on Railsの特集号を作る

### ISSUE THREAD

**Issue by miyohide** [rubima/magazine.rubyist.net#309]
今年はあまり通常号を発行できそうにないので、こういう特集号でも出していこうかと。Twitterとかだと流れてしまって後から振り返れないのはちょっともったいないという思いから。でもあまり体力はかけられない。

スケジュールとしては、

- 2020年9月15日〜21日　：　とりあえず何らかのページを出す。公式へのリンクとか？
- 2020年9月22日〜10月2日　：　各種発表者などの事前エントリーなどへのリンクを貼る？　
- 2020年10月3日（土）：　開催

という感じかな？1週間ぐらい後ろ倒ししてもいいかも。

雰囲気としてはRubykaigi直前特集号のように

- 公式ページ
- 発表者が書いてくれた事前エントリー
- 発表後日談
- 参加レポート記事

などへのリンク集ぐらいになる感じを想定。

**Comment by okuramasafumi** [comment]
チーフオーガナイザーの大倉です。
特集号の存在はとてもありがたいです、なにか私達にできることがあればおっしゃってください！

**Comment by miyohide** [comment]
@okuramasafumi ご協力感謝です。まずはページを作りますので「これを載せたらどうか」とかご意見いただけましたら助かります。

**Comment by miyohide** [comment]
とりあえず以下のページを掲載することにした。
https://blog.agile.esm.co.jp/entry/kaigi-on-rails-stay-home-edition

**Comment by okuramasafumi** [comment]
来週に銀座Railsで松田さん、ogijunさんと私で座談会をやるんですが、主催の河野さんから許可をいただければそれの文字起こしを載せても面白いかも、なんて考えました。
https://ginza-rails.connpass.com/event/186723/

**Comment by okuramasafumi** [comment]
本編の前にはあまりコンテンツっぽいものを用意できるかは怪しいですが、本編後であれば色々用意できそうな気がします。

**Comment by miyohide** [comment]
了解しました。本編後でもOKです。登壇者・スタッフさん・参加者のそれぞれのブログを載せる形で充実させていけたらと考えています。

**Comment by okuramasafumi** [comment]
本編前に用意できそうなコンテンツとして、明日開催される銀座Rails（https://ginza-rails.connpass.com/event/186723/）のコーナーである『ここに注目！Kaigi on Rails』の文字起こしがあるのを思い出しました。
最大の問題は誰が文字起こしをするのかですが…

**Comment by miyohide** [comment]
文字起こしについては、業者に頼むということができます。ですが、推敲無しで出せるものではないのでちょっと今回はパスしたいです。

**Comment by okuramasafumi** [comment]
わかりました！

**Comment by miyohide** [comment]
おかげさまで無事リリースできていますので本件閉じます。
