### ISSUE TITLE
とちぎRuby会議09レポート

### ISSUE THREAD

**Issue by vestige** [rubima/magazine.rubyist.net#311]
無事に開催できたので、レポートを用意してもらっています。

レポート担当
@tkojitu

**Comment by vestige** [comment]
原稿はここに書いてもらっているのですが、また例によってプルリクださないとですよね？

https://gist.github.com/tkojitu/88a69cdeb35c3a16ecae568c0701529a

**Comment by miyohide** [comment]
@vestige @tkojitu はい。プルリクエストを出してください。記事はマークダウンそのままではなく、いくつかの定型的な記述が必要ですので、過去記事などを参照してご確認ください。
原稿の最後には「著者について」の記述をよろしくお願いします。

**Comment by snoozer05** [comment]
@vestige @tkojitu こんにちは！こちらについて https://github.com/rubima/rubima/pull/486 でのやり取りを確認させていただき、るびまへの掲載がタイミングが合わず[個別に公開](https://tkojitu.github.io/TochigiRubyKaigi09Report/)いただいているという状況を理解しました。
るびまについて次の号が出せそうな機運が高まっておりまして、よければ同内容をるびまにも掲載させていただければと考えているのですが、ご了承いただけますでしょうか...??
ご了承いただけましたら、原稿を元に私の方で掲載までの作業をやってみるようにいたします（最終的な確認や不明点がある場合に問い合わせさせていただくくらいのお手間をいただくかと思います）。
お手数をおかけしますが、ご確認いただけますと助かります 🙏

**Comment by vestige** [comment]
気づくのおくれてしまって、すいません！
 ぜひ、るびまにつかってください、問題なしです。

**Comment by snoozer05** [comment]
ありがとうございます！

**Comment by snoozer05** [comment]
続きは #381 or #353 ですることにしてこのissueは閉じてしまいます
