### ISSUE TITLE
るびまを再開したい

### ISSUE THREAD

**Issue by takkanm** [rubima/magazine.rubyist.net#352]
みなさん、ご無沙汰です。

先日行われた [福岡Rubyist会議03](https://regional.rubykaigi.org/fukuoka03/index.html)にて、@znz さんが [Rubyist Magazine Reboot](https://slide.rabbit-shocker.org/authors/znz/fukuoka03-rubima-reboot/) という発表をされました。[日記](https://blog.n-z.jp/blog/2023-02-18-regional-rubykaigi-fukuoka03.html)にもあるように、参加者の方からもいろいろな意見がでていたようです。

私のほうでも、以下の理由で Rubyist Magazine の新しい記事をだせないか考えていたところでした。

1. [プログラミング言語Ruby30周年記念イベント](https://30.ruby.or.jp/)のような記念となるものは記事として残っているとよさそう
2. 以前のように RubyKaigi についての書かれた記事がポイントされるような場所があったほうがよさそう

なので、このタイミングで再開するために動けないかと思って、issue をあげることにしました。

中身についての具体的な案はないですが、62号のとりまとめと(やれるなら)RubyKaigi特別号の進行は、私がとりたいと思っています。
後日、各号についての issue を立てようと思います。

たぶん、みなさんが思っている課題点などがあると思いますので、まずコメントしていただけると嬉しいです。

あと福岡 Rubyist 会議03 に参加されたかたで、るびまについての意見を聞いた方は、軽くここにコメントしていただけると助かります。

**Comment by miyohide** [comment]
@takkanm  ご無沙汰しています。最近全然動けてなくてすみません。

62号のとりまとめや（やれるなら）RubyKaigi特別号の進行ですが、是非お願いしたいです。

現状の課題点は色々とあるかと思います。一度整理してお話しさせていただければと思います。取り急ぎ、ご連絡まで。

**Comment by kakutani** [comment]
30周年イベントは明日(あした!)だし、RubyKaigiは5月でその前に連休があるしもし特集号を事前に出すならその前に出さないといけないなら準備はその前に必要だし、でタイムラインがタイトですね。各位助けてくれ〜 🙏 

福岡Rubyist会議03の @znz のトークでも触れられていたことで、ひとつお知らせ?というかおうかがいというか。

https://slide.rabbit-shocker.org/authors/znz/fukuoka03-rubima-reboot/14
(TIL: Rabbitのスライド画像へのリンクはゼロオリジン)
![image](https://user-images.githubusercontent.com/2160/221056913-80039223-be44-4e71-981b-92aade848564.png)

宙ぶらりんになっているな、というのは地域Ruby会議オーガナイザー同士の連絡手段も同様で、
日本Rubyの会のDiscordサーバーがあるので(理事の連絡とかミーティングに使っている)、それを活用したいねという話を少しずつ進めてました。

[ruby-jpのSlack](https://ruby-jp.github.io/)は有志の運営だしログも残らないし外部連携にも上限があるし、Rubyの会で応援しているプロジェクトのコミュニケーションチャンネルは会でホストしたほうがいいかなあと思ってます。

これまで理事たちでしか使ってなかったので、不備はありそうですが、そのあたりも追々準備していければなーと思ってます(いったん↑に出てきている登場人物の皆さんにはinvitationを送ります)。

**Comment by emorima** [comment]
先日、ぷぽさんとお会いした時に、るびまの話がでて、
Rails Girls Tokyo Tokyo 14th の開催時に、るびま書きたいな～と思ったという話をしていたのでした！
私も再開して欲しいと思っていますし、お手伝いします！

RubyKaigi直前号ももちろんなのですが、
各地域コミュニティ探訪コーナーとか面白いかも？と思いました。
コロナになってからコミュニティに入ってきた方に、知ってもらって参加してもらえるきっかけになったり、
最近の活動を知ってもらうのもよいのではと思います！

**Comment by neko314** [comment]
@takkanm
明日の開催レポートなら私でよければぜひやりたいです！

2つほど他の方の協力を仰ぎたい点があります。

1つ目
私は明日リモートで一人でみる予定なのですが、踏まえて現地会場など、物理的に開催したり集まったりしているところにいる方々に写真をとっていただいて提供いただけると良いものになると思います。
そのためには現地の方々に写真撮っていただくようにお願いしたり、当日「写真載せるかもしれませんがいいですか」と開催に当たってご案内いただくなどの必要も出てくると思います。まずはその辺のあれこれを @takkanm とお話ししたいです。

2つ目は可能だったらくらいではあるのですが、自分一人だと聞き逃したりしそうなので、もう一人くらい一緒にやったり、あるいはチェックいただける方がいると心強いです。どのみちPRにレビューしていただくことになると思うので、それで良いかもしれませんが、私の気持ちの問題。。。

**Comment by snoozer05** [comment]
> あと福岡 Rubyist 会議03 に参加されたかたで、るびまについての意見を聞いた方は、軽くここにコメントしていただけると助かります。

福岡Rubyist会議03にて、znzさんの話を受けて質疑応答にて意見（というよりは現状のdump）をした者です。

福岡Rubyist会議03にてみんなにお話したのは次のような内容でした:

* 前提として「るびま」というメディアが残るといいなと思っている
* けれど、続けていくというのは簡単ではないことで、この後、人が集まってきて続けていけるようになるには、単に「これまでやってきたこと」をやっていくというのは難しいのではないか
* なぜなら、るびまを始めた当初とは状況が色々と変わっている部分があるから
* 例えば...
   * 商業誌でRubyの記事が書けなかった→書けるようになった
   * 個人のブログで記事を書くよりも編集が入った記事を執筆できる→技術記事などは個人ブログよりも企業ブログで出すことも多くなってきていて（そちらにノルマなどもあったりすることから）、単純なメリットとは言いづらくなってきている
   * RubyEventCheckを見てイベントの情報収集をしていた→情報を知る手段は増えて、ここを情報収集で見ることは無くなった。一方でイベント数は増えメンテナンスは大変になっていった
* では、るびまの価値はなんだろう、というのを個人的に考えてみると、それは「号として記事がパッケージされたものが積み重なって行くことで、後から見たときに当時のコミュニティの気分、雰囲気がアーカイブされているという歴史的価値」「Rubyコミュニティの雰囲気のスナップショット」のようなものなのではないか
   * こんな技術にみんな興味を持っていた
   * こんなイベントがあった
   * ...
* こうした観点で改めてるびまを捉え直して、そのためにどんな記事をどんなスパンでどのように出していく、というのをみんなでまた考えて行くというのが、るびまのrebootになるのではないか

これを受けて、Hotlinks読みたいと思っているというご意見や、企業で書いた記事を転載して行くのはどうかといったご意見などが会場で見られていたというのが、福岡Rubyist会議03のznzさんの質疑応答で起きていたことになります。

**Comment by hsbt** [comment]
* GitHub の設定などで、今だとリポジトリを分ける必要がなかったりするのでその辺はやっておきます(継続してやります)。
* 記事の寄稿、編集長(進行役?)まではやる余力はありませんが、単一の記事の編集/レビューはやります。

**Comment by jinroq** [comment]
福岡 Rubyist会議 03 を主催した者です。

今回るびまがリブートすることを事前に知っていたので、るびま寄稿用に記事を書いてくれるメンバーは用意していました。
後日寄稿できるようにする予定です（お作法はよく分かっていませんが）。

**Comment by hasumikin** [comment]
@neko314 
> 現地会場など、物理的に開催したり集まったりしているところにいる方々に写真をとっていただいて提供いただけると良いものになると思います。

松江会場の写真、わたくし撮ります（会場にいる人たちに肖像権の確認します）。記事のチェックもやります

**Comment by neko314** [comment]
@hasumikin 

ありがとうございます！お願いします🙏🙏🙏

**Comment by hsbt** [comment]
> 今回るびまがリブートすることを事前に知っていたので、るびま寄稿用に記事を書いてくれるメンバーは用意していました。
> 後日寄稿できるようにする予定です（お作法はよく分かっていませんが）。

https://github.com/rubima/magazine.rubyist.net/tree/master/articles/0061/_posts

みたいな感じで md をとりあえず入れておけばよさそうです。細かいところはそのうちで。

**Comment by kakutani** [comment]
盛り上ってきた!! Rubyの会のDiscordのinvitation urlを置いときます: https://discord.gg/ygbBBKuzuH
(無期限上限ナシの招待リンクなので、必要そうな方に教えてもらってかまわないです〜。いちおう編集・進行・相談用のつもりですが、運用もまあ相談しながらで…)

**Comment by takkanm** [comment]
みなさん、ありがとうございます。

とりいそぎ、記事よろしくお願いします！！ >  @neko314, @hasumikin, @jinroq, @emorima (敬称略)
後ほど、62号用に issue たてて、ポイントします。

**Comment by miyohide** [comment]
書き方はREADMEを参照していただけますとざっくりしたものは把握できるかなと思います（だといいなぁ）。

https://github.com/rubima/magazine.rubyist.net/blob/master/README.md

他の記事も併せて見ていただけるとより理解が深まるかと思います。

細かい点や英語名などについては都度ご連絡いただければ。

**Comment by hsbt** [comment]
https://github.com/rubima/magazine.rubyist.net/discussions/364#discussioncomment-5137900 に自己紹介スレを移動してみました。
