### ISSUE TITLE
62 号をだす

### ISSUE THREAD

**Issue by takkanm** [rubima/magazine.rubyist.net#353]
## 決めること

* [ ] いつリリース目標とするか
* [ ] 記事をどれぐらい用意するか

## リリース時期

* 記事締め切り: 4/20 頃
* リリース: 4/20 頃にできた記事をベースにリリース準備でき次第

## 記事候補

| | 記事予定 | 寄稿者(敬称略) | 対応 PR |
|:---:|:---|:---|:---|
| 1 | 巻頭言 | @takahashim  | #401  |
| 2 | プログラミング言語Ruby30周年記念イベント開催レポート | @neko314 , @hasumikin  | #385 |
| 3 | とちぎRuby会議 09 レポート | @tkojitu |  #381  |
| 4 | 福岡 Rubyist会議 03 レポート | @MasayaNishijima @jinroq  | #384 |
| 5 | 訳者による『研鑽Rubyプログラミング』の紹介 | @kakutani | #398 |
| 6 | Rails Girls Tokyo 14thレポート | @emorima | #399 |
| 7 | 編集後記 | ??  | |

## To Be Continued... ⏩

* YARV Maniacs, @ko1 https://github.com/rubima/magazine.rubyist.net/issues/353#issuecomment-1512093784

**Comment by takkanm** [comment]
@neko314 @hasumikin @jinroq 今回は寄稿予定ありがとうございます。

記事の出し方についてですが、[README](https://github.com/rubima/magazine.rubyist.net/blob/master/README.md)を読んだところ、リリース日が決まらないとファイル名が決まらないということがわかりました。とはいえ、現状不明瞭なところも多いので、決まるまでは以下のように PR をだしていただけたら、merge 後なり、なんなりこちらで修正して出せる形にもっていきたいと思います。

* 記事の markdown は `articles/62/_posts/2023-04-01-62-#{記事名}.md` というファイル名にする
  * 4/1 にだすというわけでなく、ここが決まっていないとローカルに環境組んでプレビューできないかと思い、適当な日付にしています
  * 地域 RubyKaigi のレポートのファイル名は `hogehogeRubyKaigiXXReport` となっていることが期待されているが、これは福岡 Rubyist 会議 03 というネーミングとコンフリクトしているので一旦 `FukuokaRubyistKaigi03Report` のように会議名をそのままつかってください > @jinroq
    * あとは個人的なお願いですが、今回の会議の名前のコンベンションが変わった理由や熱い思いなどを知りたかったのですが、公式サイトにのってなかったので、その辺りが語られていると個人的には嬉しいです。
* 画像ファイルは `/images/62-#{記事名}/` というディレクトリを作り、そこにいれてください https://github.com/rubima/magazine.rubyist.net/tree/master/images/0061-HeiseiRubyKaigi01Report
  * 画像のファイル名や形式についてのコンベンションは無いという認識です。
* Markdown ファイルにいれるメタデータについては、以下のようにしてください
  *  tags については、とりあえずなくてよいです
    * どういったタグがあるか、新規にタグつくるとどうなるかを調べて、わかり次第展開します
  * created_on は 2023-04-01 としてください
    * こちらも日程を決め次第、変更します

他、わからないことや不安なことなど、ささいなこともでも聞いてください。

以上、よろしくお願いします。

**Comment by ko1** [comment]
久々に YARV Maniacs 書かせてください

**Comment by takkanm** [comment]
@ko1 お願いします!!

**Comment by kakutani** [comment]
### 地域Ruby会議の名称の命名規約を緩和したい話

> * あとは個人的なお願いですが、今回の会議の名前のコンベンションが変わった理由や熱い思いなどを知りたかったのですが、公式サイトにのってなかったので、その辺りが語られていると個人的には嬉しいです。

記事でどう書くかはそれはそれとして、情報提供として。
「公式」にまとめる予定ではありますが(「公式」とは…というのは後述)、背景や意図については
「地域Ruby会議名の命名規約を変更(緩和)したい」( ruby-no-kai/official#448 )に書いてはあります。

### 公式をScrapboxに移そうとおもってます(ちょっとずつやってる)

「公式」のWikiは現状のGitHubのWikiからScrapboxに移行しようと思ってます。
https://github.com/ruby-no-kai/official/wiki というURLが大好きなんですけれども、
地域Ruby会議が「戻って」きたときにガイドライン等をひさびさに更新しようと思ったら
書き味がとても辛かったので…。
道具のせいにするのもどうかと思いますが、続けやすそうなところに移りたいと思ってます。

### 「公式」に移動に伴なってRubyEventCheckもscrapboxに移そうと思ってます

2023年は https://scrapbox.io/ruby-no-kai/RubyEventCheck を更新してます。
るびまからリンクしてもらうならscrapboxのほうにリンクしてもらえるとよさそうです。

**Comment by kakutani** [comment]
記事候補…。

枯れ木も山の賑いということであれば4月あたりに『 [研鑽Rubyプログラミング](https://www.lambdanote.com/collections/ruby/products/products-polished-ruby-beta) 』の正式版が出るはずなので、何か寄稿する(か、フォールバックとして「訳者あとがき」などを丸ごと載せることができそうです)。
書いてくれる人がいるならどなたかにレビューを書いてもらえると良さそうですが、ちょっと締切がタイトだよな…。

**Comment by okuramasafumi** [comment]
#340 を立てた者です。記事を書きたい気持ちはまだあるので（issueについてはすっかり忘れていましたが…）、間に合いそうなら記事を書きたいです（もし記事の数が足りているようでしたら次号でも）。
内容は、自作のgemがそこそこ使われるようになるまでにやったこと、みたいなテーマが思いつくのですが、他の内容でも可能です。

**Comment by neko314** [comment]
@takkanm
@hasumikin

4/1で一旦作っていく件了解ですー
62号の発行日は未定かと思いますが、自分としては期限を持たないと終わらなそうなので、3月半ばくらいまでに30周年の記事書いておきたいと思っています。（と明言することで追い込んでいく...!)

**Comment by snoozer05** [comment]
３年越し?ですが、#311 も載っけられると良さそう？

**Comment by MasayaNishijima** [comment]
福岡 Rubyist会議 03 レポートを書かせて頂く者です。連絡が遅れ申し訳ないです。

>今回るびまがリブートすることを事前に知っていたので、るびま寄稿用に記事を書いてくれるメンバーは用意していました。
後日寄稿できるようにする予定です（お作法はよく分かっていませんが）。
>>https://github.com/rubima/magazine.rubyist.net/issues/352#issuecomment-1443132696

こちらで上げられているのが自分です。

記事の方はまだ半分ほどしか書けていないので、書けましたら再度連絡させていただきます。

大勢に見られる文章を書くことが、初めてでお手数おかけすることもあると思います。
何卒、よろしくお願いいたします。

**Comment by emorima** [comment]
4/1 予定であれば、昨年7月開催のRails Girls Tokyo 14thの開催記事書きたいです！
(4/7-8 Tokyo 15th, 4/14-15 Nagasaki 1st開催も控えてるので...)

**Comment by kurotaky** [comment]
鹿児島Ruby会議02のレポートを載せたいです。
https://twitter.com/kurotaky/status/1632397653274398721 で声かけてもらったので、
@okuramasafumi さんと一緒に書けると嬉しいです〜

**Comment by okuramasafumi** [comment]
鹿児島Ruby会議02のレポートを書くに当たって、当日の会場の雰囲気がわかるような写真が何枚かあるとよいかなと思っています。私は（会場内の）写真を1枚も撮っておらず…
@kurotaky 運営のどなたかが写真をお持ちでしたら共有していただけるとありがたいです！

**Comment by kurotaky** [comment]
@okuramasafumi 
K-RubyのSlack上で集めているところです。Google Photos のURLも共有しました！

**Comment by kakutani** [comment]
> * いつリリース目標とするか

記事を書くついでに『研鑽Rubyプログラミング』の読者プレゼント的なやつをやろうかな〜と思ったのですが、リリース目標っていつ頃にする感じですかねえ… @takkanm

**Comment by takkanm** [comment]
各位 ちょっと反応等が遅れてしまいすみませんでした。

@kurotaky @okuramasafumi @emorima 立候補ありがとうございます！

いろいろ事前のプロセスを思い出したところ、どう考えても 4/1 は無理そうなので、4中旬から4末にかけてが現実的なターゲットかなぁと思っています。

> 記事を書くついでに『研鑽Rubyプログラミング』の読者プレゼント的なやつをやろうかな〜と思ったのですが、リリース目標っていつ頃にする感じですかねえ…

これはリリース日が何かしらマターになりそうですかね？出版日とかいろいろセンシティブなことがあるのかもしれないのでパブリックで話づらい場合は、DMなりなんなりで話しましょう > @kakutani

**Comment by kakutani** [comment]
> これはリリース日が何かしらマターになりそうですかね？出版日とかいろいろセンシティブなことがあるのかもしれないのでパブリックで話づらい場合は、DMなりなんなりで話しましょう > @kakutani

4月中旬〜末ぐらいなら、ちょうど配本されるぐらいの時期なので、なにか問題になるということもなさそうです。
↑この時期だと、 #352 にあった「RubyKaigi特別号」の進行は難しそうだな…とおもいました(元々「やれたら」とあったので、やれないならやらない、でよさそうだけど)。

**Comment by neko314** [comment]
@hamakn 
自分が言った期日に対して大変遅くなっております🙏
まだまだ半ばですが進捗共有のために #385 立てました。もうちょっと（だいぶ？）かかりそう。がんばります。

**Comment by okuramasafumi** [comment]
#392 進捗共有のためのPRを作りました。

**Comment by snoozer05** [comment]
@takkanm 高橋さんに巻頭言のこと伝えました。書く必要があるというのは認識していたがまだ書けていないというステータスとのこと

**Comment by hsbt** [comment]
ブロッカーではありませんが、62号までに https://github.com/rubima/magazine.rubyist.net/issues/370 流行っておこうと思います。

**Comment by takkanm** [comment]
@MasayaNishijima @neko314 @emorima @kurotaky @okuramasafumi @ko1 @kakutani 
4 月に入ったので、そろそろ締め切りを決めてしまいたいと思います。
記事をお願いする立場から、こういう依頼をするのも心ぐるしいですが、以下のようにさせていただきたいと思います。

* 記事締め切り: 4/20 頃
* リリース: 4/20 頃にできた記事をベースにリリース準備でき次第

**Comment by ko1** [comment]
ちょっと書いてみたんですが、あんまりおもしろくならない（面白くなるまで書くのが大変だった）ので今回は見送ります。次回こそ...。

**Comment by takkanm** [comment]
@ko1 了解しましたー。次回よろしくお願いします。

**Comment by emorima** [comment]
遅くなりましたが、PR出しました！

**Comment by kakutani** [comment]
#398 をopenしました。本文は「あとでかく」になっていますが、主眼は読者プレゼントなので、フォームや応募〜発送の流れが大丈夫そうか主に見てもらいたいです。
(「あとでかく」のまま :shipit: でもいいんじゃないかな〜と思ってます)

@emorima Descriptionを更新しておいてもらえるとよさそうです(記事の追加)

**Comment by emorima** [comment]
@kakutani Description のEditが出てこなくて編集できなかったです💦
(issueの新規作成、コメント追加はできるけど、Description編集はできないようです...)

**Comment by kakutani** [comment]
そうなのか…権限のことをはあくしてなかった…😇

**Comment by kakutani** [comment]
@takkanm @emorima には<<パワー>>を与えてよいのでは? と思うんですが、いかがでしょう

**Comment by znz** [comment]
@emorima invitation を送ったので、確認をお願いします。

**Comment by emorima** [comment]
@znz invitation届いてjoinしました！ Editリンクも確認できました。ありがとうございます～

**Comment by takkanm** [comment]
記事締め切り後の備忘録

* 簡易的にテキストルールに従うように各レポートを修正
* 表紙作成 https://github.com/rubima/magazine.rubyist.net/blob/master/articles/0061/_posts/2020-02-02-0061-index.md
* 編集後記 https://github.com/rubima/magazine.rubyist.net/blob/master/articles/0061/_posts/2020-02-02-0061-EditorsNote.md
* 地域 RubyKaigi レポートがバックナンバーでまとまる要件をみたしているかチェックhttps://github.com/rubima/magazine.rubyist.net/blob/master/articles/backnumber/_posts/2000-01-01-backnumber.md#regionalrubykaigi%E3%83%AC%E3%83%9D%E3%83%BC%E3%83%88
* RailsGirls 開催レポートが今回で 3 つめっぽいので地域 RubyKaigi レポートのようにバックナンバーにまとまめるか考える
  * 次号も貰えそうなので次号でもいいかもしれない

**Comment by kakutani** [comment]
> * 編集後記

無茶振りな気もするけれど、 @miyohide に0062発行にあたっての感想というかお気持ちを寄せてもらえるといいなと思いました!!

**Comment by neko314** [comment]
@takkanm @hasumikin

> 残酷なことに締め切りが過ぎているため、そろそろ 62 号に含めるかどうかの Go/NoGo を決めたい

そうですよね😇

30周年のレポート、今の時点で見送りとさせていただけないでしょうか。

直しがまだという理由もありますが、それ以上に、[登壇者の皆様に文字起こしして掲載する旨ご連絡する](https://github.com/rubima/magazine.rubyist.net/pull/385#issuecomment-1517060798)件の方で、26(水) 中に出して良い状態になると言い切れないかと思い。
とりあえず掲載までにやるべきことと現状整理してみます。

次号があって当然、とは思ってないですが、次号には載せたいです。

**Comment by kakutani** [comment]
> しかし、残酷なことに締め切りが過ぎているため、そろそろ 62 号に含めるかどうかの Go/NoGo を決めたいと考えおります。急で申し訳ないですが、26(水) 中を目処に終わらなそうであれば今号の掲載は見送らせていただければと思います。

#398 に書いた通り、記事の「本体」は読者プレゼントなので、0062号 に入れてほしいです!

**Comment by okuramasafumi** [comment]
@takkanm 鹿児島Ruby会議02の記事は、本文の内容に関しては完成した認識でいます。
画像については、現状8人いる登壇者のうち1人の分の画像がない状態で、作業を進められずにいます。
画像は @kurotaky が持っていると思いますのでGitHub上で問い合わせています。

ですので、画像なしならGoでいいと思っています。画像はもし後から追加できるようでしたらそれでもよいのかなと個人的には考えていますが、いかがでしょう。

**Comment by takkanm** [comment]
@neko314 お気持ちの表明了解しました。次号お願いします。その際は、気になるポイントとかあれば一度 sync 等できると思いますので、いつでもいってください。

@kakutani @okuramasafumi 今号にいれる、かつ記事の done のスコープ了解しました。期日がすぎましたので、いったんここで作業をフリーズ願います。わたしのほうで、校正の作業を行うためです。 e.g., https://github.com/rubima/magazine.rubyist.net/commit/c24b926914d2c9493904700cac54121fed142084

**Comment by kakutani** [comment]
書くだけ書いたという状態で、ガタガタだけどタイムアップということで、 67f5dfc81b8f8631d3d49c3515733b51900f5a96 でいったん手放します〜 🙏 @takkanm

**Comment by kurotaky** [comment]
@okuramasafumi 
https://github.com/rubima/magazine.rubyist.net/issues/353#issuecomment-1521141722 の件ですが、
写真を見つけました！ https://github.com/rubima/magazine.rubyist.net/pull/392#issuecomment-1526940156 でコメントしました。

**Comment by takkanm** [comment]
@MasayaNishijima` @emorima @kurotaky @okuramasafumi  @kakutani  @snoozer05 @hsbt  @takahashim 

記事の執筆、編集、環境の見直し等、みなさま協力ありがとうございました。
記事自体は個別にインターネットからは見られるようになっており、本日の夜(可能であれば 18 時頃、無理目なら 20 時台)に表紙と編集後記をだして、リリースとしたいと考えております。

もうしばらく、お付き合いください。

**Comment by takkanm** [comment]
@tkojitu @MasayaNishijima @emorima @kurotaky @okuramasafumi  @kakutani  @snoozer05 @hsbt  @takahashim 

62 号だしました。みなさん、もろもろのサポートありがとうございました。

@ko1 , @neko314 もご協力ありがとうございました。

**Comment by hsbt** [comment]
@takkanm グレートワークお疲れさまでした!11
