### ISSUE TITLE
rubima/rubima をアーカイブしておく

### ISSUE THREAD

**Issue by snoozer05** [rubima/magazine.rubyist.net#354]
https://github.com/rubima/rubima にある以下の記載のとおり、現在は本リポジトリが本拠地となっています。

> るびまのリポジトリは以下のリポジトリに移行しました。
https://github.com/rubima/magazine.rubyist.net
記事の寄稿やご指摘については上記のリポジトリに対してIssueを作成していただくか、Pull Requestを発行していただくようお願いします

ですが、https://github.com/rubima を開くと以下のような文言が目に入るため、初めてやってきた人はどうしてもまず rubima/rubima を開いてしまうと考えます（こっちがただの原稿置き場に見えてしまう）。

* rubima/rubima: るびまの編集リソースを集めたり進行状況を確認するリポジトリです
* rubima/magazine.rubyist.net: magazine.rubyist.netで公開しているるびまのJekyll版です

なので、この辺りを現状に即した形にメンテナンスしておこうと思います。
具体的には

* rubima/magazine.rubyist.net の説明を「るびまの編集リソースを集めたり進行状況を確認するリポジトリです」にする
* rubima/rubima の説明を「以前るびまの編集リソースを集めたり進行状況を確認していたリポジトリ」にしてリポジトリをアーカイブする

と、ここまで書いて rubima/rubima にしかないリソースがあることを見つけてしまった...（https://github.com/rubima/rubima/blob/master/editing_policy.md や https://github.com/rubima/rubima/blob/master/license.md など）。この辺りはこっちに持っておきておいた方が良さそうなので、別でissue切っておこうと思います。

本issueではひとまずリポジトリの動線の改善のみ対応します

**Comment by snoozer05** [comment]
<img width="958" alt="スクリーンショット 2023-02-28 7 23 10" src="https://user-images.githubusercontent.com/3954/221699531-d0754692-a7c5-44ba-87f2-254777735904.png">

対応しました。これでorgに来た人が迷うことはなさそう

**Comment by hsbt** [comment]
リポジトリの pin を変更してトップには来ないようにすると良さそう、と思い設定眺めたんですが見当たらない...。

**Comment by snoozer05** [comment]
https://github.blog/changelog/2022-04-29-pin-repositories-to-public-or-member-org-profile-from-repo-page/ これに沿ってこのリポジトリをpinしてみました！

**Comment by hsbt** [comment]
🙏 

pin する UI が変わっていた...

**Comment by hsbt** [comment]
@snoozer05 rubima/rubima のいくつか今も継続してそうな issue を transfer しておきました。obsolete だよね、ということならシュッと close で。

**Comment by snoozer05** [comment]
ありがとうございます！
