### ISSUE TITLE
るびま読者向けのライセンスについて考える

### ISSUE THREAD

**Issue by miyohide** [rubima/magazine.rubyist.net#356]
読者さんより指摘。

るびまのライセンスは https://github.com/rubima/rubima/blob/master/license.md に記されているが、利用者向けのライセンスが記述されていないという指摘。以下、指摘の引用。

> るびまの利用者がどのようなライセンスの元に記事を利用できるかというケースに
> なりますので、上のライセンス条項ではカバーされないのではないと判断しましたが、
> いかがでしょうか。
> Webで公開されているものは容易に複製、再配布が可能ですので、上のライセ
> ンス、および公開ページ内にも、_利用者に対するライセンス_が記載されてい
> ることが望ましいと思います。

**Comment by ko1** [comment]
#361 などを見ると、英語に翻訳する権利ももらえたらもらっておくといいのかなぁ。

**Comment by snoozer05** [comment]
> https://github.com/rubima/magazine.rubyist.net/issues/361 などを見ると、英語に翻訳する権利ももらえたらもらっておくといいのかなぁ。

現状のlicense.mdには

> 編集部は他の言語などに翻訳し、それを複製・配布する非独占的な権利を得る

とあるので、編集部がこれをする分には問題なさそう。

次に、サイトに

> 掲載記事の著作権は各記事の寄稿者にあります。再頒布等については編集部までお問い合わせください。

というのは、書く必要があるかなあ（今回もそうであったように、普通にそうするのでは）と思うので、いったん閉じて様子を見るで良いかなと思いました（いったん閉じちゃいます
