### ISSUE TITLE
編集コミュニティに新しく来た人のための手続きを明確にする

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/magazine.rubyist.net#359]
- 編集MLへ登録する
- 編集コミュニティにようこそメールを送る（編集Wikiの使い方とかが書いてあるやつ）
- GitHubのrubima/ownersに登録する

あたりでしょうか。とりあえず今回のインタビューから新しくメンバーになってくれることになった @hamakn に対する一連の手続きをやってみて手順書化するといいのかなあ。

see https://github.com/rubima/rubima/issues/22

**Comment by snoozer05** [comment]
このissueが立ったときとは状況が変わっているので整理してみます。

## 現状の編集コミュニティへの参加の流れ

- このリポジトリに辿り着く
   - 💭 そのための動線を増やした方が良いかもしれない。るびま本体に書くとか。けどまたそれは別の話
- READMEから https://github.com/rubima/magazine.rubyist.net/blob/master/CONTRIBUTING.md#るびまを刊行するお手伝いがしたい に到達する
   - 自己紹介をして、Discordに入ってもらう
- Discordやissue上で会話して、手を出せそうなissueがあったら、編集してもらったりリポジトリをいじってもらったりする

という感じかな。あとは誰かの紹介で編集に来たとかあれば、それは紹介者がDiscordなりでフォローして貰えば良さそうだし、明確にすべき手続きは全て明確になっていそう。

Discordのチャンネルにもう少し情報を増やしていてもいいかもしれないが、それもまた別の話なので、このissueについては対応が不要になったという結論でよさそうに思いました。

一旦閉じてしまいますので、何か気になることがある人がいたらreopenかissue立てをお願いしますー

**Comment by kakutani** [comment]
> * そのための動線を増やした方が良いかもしれない。るびま本体に書くとか。けどまたそれは別の話

別の話だけど、るびま本体のどこかに書いておくのは良さそうですね。FAQとか?

**Comment by snoozer05** [comment]
FAQよさそうですね！ちょっと考えてみますー
