### ISSUE TITLE
問い合わせ先として discussions を使う

### ISSUE THREAD

**Issue by hsbt** [rubima/magazine.rubyist.net#360]
現在は https://github.com/rubima/rubima-support がありますが、 https://github.com/rbenv/ruby-build/discussions のように質問や close 条件が定まらないものを放り込む先としてこのリポジトリの discussions を使うのはどうでしょうか

**Comment by kakutani** [comment]
さんせい〜👍

**Comment by snoozer05** [comment]
良さそう！

**Comment by hsbt** [comment]
rubima/rubima-support をアーカイブしてそれっぽい誘導をつけておきました。Discussions の入り口のお手入れはまた別途やっておきます。
