### ISSUE TITLE
リリース(デプロイ)手順を楽にする

### ISSUE THREAD

**Issue by hsbt** [rubima/magazine.rubyist.net#366]
いわゆる GitHub お馴染みの

* PR 作る
* レビューする/手直しする
* merge する
* デプロイされる

というだけのフローに近づけようと思います。まずはこのリポジトリだけで完結するというところを目指します。

上記の merge する/デプロイされる の間には進行役による「確認する/リリースする」というフローが必要と思いますが、その仕組みはちょっと後で考えます。単純には jekyll の `published: false` を執筆中のページにはつけて、進行役がそれらを true にしたらリリース、というあたりを想定しています。

**Comment by hsbt** [comment]
設定を変更して https://magazine.rubyist.net/ は https://github.com/rubima/magazine.rubyist.net/actions/workflows/jekyll.yml でデプロイされたものになってます。

**Comment by hsbt** [comment]
https://github.com/rubima/rubima.github.io は README.md を作って、昔のコンテンツですよ、と書いておきました。

**Comment by takkanm** [comment]
> 上記の merge する/デプロイされる の間には進行役による「確認する/リリースする」というフローが必要と思いますが、その仕組みはちょっと後で考えます。単純には jekyll の published: false を執筆中のページにはつけて、進行役がそれらを true にしたらリリース、というあたりを想定しています。

このあたりを #asakusarb で話していたんですが、号のトップページなりなんなりからリンクされていなければ、別にパブリッシュされていていいのではという話をしていました。あとは、リリースまでマージしないという運用もありかなという話をしてました。

**Comment by hsbt** [comment]
すでに GitHub で public なものなので、一生懸命読もうとする人がいればいくらでも読めるし頑張らなくていいな、って話をしました。それはそう、なので頑張らないことにします。

**Comment by kakutani** [comment]
Continuous Deploymentで`published`をFeature Toggleとする、というモダンな感じでよさそう(熱心に生原稿の段階から読む人は原稿もレビューしてくれ…!!)。

10年以上経ってから参照されることにめちゃめちゃ価値があるので、publishされる前の原稿が見えたからといって「それはそう」でよさそうですねえ。

**Comment by hsbt** [comment]
リリース、2パターンありそうな気がしました。

* いわゆる feature branch を 62 号まとめ、みたいにして作って、そこにまとめてから master へ、とする
* 上に書いたように master にドカドカマージして、進行役が最後に表紙を作る

どちらでも良さそうですが、手順に反映はしとくと執筆する人が pr を出す先に迷わなさそうです。

@takkanm どうしますかねー

**Comment by znz** [comment]
リリース前の確認用のプレビューサイトをどうするかというのにも関わってきそうなので、 staging deploy のやりやすさも考えた方が良さそうだと思いました。

**Comment by hsbt** [comment]
@znz github-pages を使うようにしてから staging deploy, ということはやってなさそうな気配でした。技術的にもリポジトリを分ける、くらいしか実現できないと思います。

おそらく、doc の下に作成して確認か、`jekyll serve` で個別にチェックしていた、って感じと思います。

**Comment by znz** [comment]
なるほど、それなら気にしなくても良さそうです。

個人blogで使っている netlify なら pull request ごとに preview サイトができるけど、 rurema の方で一度試していたら、deploy が多すぎて無料の範囲に収まらなくなってしまったことがあるので、なくてもなんとかなっているなら、がんばって使う必要はないかなと思いました。

**Comment by miyohide** [comment]
> おそらく、doc の下に作成して確認か、`jekyll serve` で個別にチェックしていた、って感じと思います。

はい。その形でやってました。

**Comment by takkanm** [comment]
> @takkanm どうしますかねー

手間が少なそうな 2 の master へドンドンでいきましょう。フローの問題かなとは思うので、どちらのやり方になっても「masterにマージ」を契機にインターネッツへ publish という感じでよいと思います。

**Comment by hsbt** [comment]
返事あざます。

`README.md` に軽く反映させておきました。これであとは書いてマージすれば出る、と言う状態にはなったのでここは閉じます。
