### ISSUE TITLE
CONTRIBUTING.md の内容が現状と一致していない

### ISSUE THREAD

**Issue by takkanm** [rubima/magazine.rubyist.net#382]
リポジトリ内のファイルを見直していて気づいたのですが、CONTRIBUTING.md の内容が現状のリポジトリの利用と一致していないと思いました。よい修正が浮かんでいないので、起票まで。
https://github.com/rubima/magazine.rubyist.net/blob/master/CONTRIBUTING.md

**Comment by snoozer05** [comment]
状況・経緯をちょっと整理してみます。

### 元々のコミュニケーション設計がどうなっていたか

- rubima/magazine.rubyist.net のissues: 編集部が記事の進行管理をする、あるいは雑多なissueを管理する場所として用意（内部のコミュニケーション用）
- rubima/rubima-support のissues: 記事の typo 指摘や、るびまへの要望などを登録してもらう場所として用意（外とのコミュニケーション用）

### 実際の使われ方はどうだったか

- 基本的にはそのように使われていたように見える
   - https://github.com/rubima/magazine.rubyist.net/issues?q=is%3Aissue+is%3Aclosed
   - https://github.com/rubima/rubima-support/issues?q=is%3Aissue+is%3Aclosed
- 執筆者が記事誤りに気がついた場合や上記を確認した場合などに限ってPRを rubima/magazine.rubyist.net に直接送ってきていそう？
   - https://github.com/rubima/magazine.rubyist.net/pulls?q=is%3Apr+is%3Aclosed をみた感じ、そんなに一般の読者の方が直接PRを送ってきているようには見えない

### 最近行った変更

当時はなかったDiscussionsを使えば、別リポジトリにコミュニケーション場所を分ける必要はないのでは、ということで外部との場所を rubima/rubima-support を https://github.com/rubima/magazine.rubyist.net/discussions に移した https://github.com/rubima/magazine.rubyist.net/issues/360

ということで、上記を踏まえると、現状のCONTRIBUTING.md の内容は現状のリポジトリの設計・利用実態とはあっているという結論になるかなと感じたのですが、どのあたりが「CONTRIBUTING.md の内容が現状のリポジトリの利用と一致していないと思った」ポイントになりそうかな。

現状に合わせたいというよりかは、 #383 のように見直したい、という気持ちだったりするでしょうか。

**Comment by takkanm** [comment]
リポジトリにコントリビュートしたい人に向けての内容が含まれていないことに違和感を感じているんだと思います。
リポジトリに存在する CONTRIBUTING.md がリポジトリに PR や Issue を立てる人向けということを考えると、想定される人というのは編集する人、記事を書く人がいるはずです。それらの人に向けてのメッセージは何もないなと。

**Comment by snoozer05** [comment]
なるほど。「書かれていないこと」についての違和感だったんですね。確かに、「編集手伝いたい」「記事書きたい」と思ってリポジトリを訪れた人にとってのメッセージがあった方が良さそうですね。

CONTRIBUTING.mdを覗く人のユースケースは大体次のような感じですかねぃ:

1. るびまを刊行するお手伝いがしたい
1. るびまに記事を書きたい
1. るびまの刊行/記事/体制その他についてアイデアがあるので提案したい
1. 記事のtypoを見つけたので知らせたい
1. 記事の問題（技術的な誤りなど）を見つけたので知らせたい

それぞれについて、どんなふうに案内をするといいかは次のような感じになるのかな:

### 0. 共通

https://github.com/rubima/magazine.rubyist.net/blob/master/CODE_OF_CONDUCT.md に目を通してね

### 1. るびまを刊行するお手伝いがしたい

* https://github.com/rubima/magazine.rubyist.net/discussions/364 に自己紹介をお願いします
* 編集部のDiscord https://github.com/rubima/magazine.rubyist.net/issues/352#issuecomment-1443682899 に参加ください
* このリポジトリやDiscord上でそのうち色々動きが出てくるので、手伝えそうなものを拾ってもらえるとありがたいです

### 2 るびまに記事を書きたい

* https://github.com/rubima/magazine.rubyist.net/discussions or https://github.com/rubima/magazine.rubyist.net/issues （#383 次第）にて書きたい記事の内容をお知らせください
   * 💭  discussions の場合はCategoryを作っておいた方が良さそう。issueの場合はラベルを用意しておくといいかな

### 3. るびまの刊行/記事/体制その他についてアイデアがあるので提案したい

* https://github.com/rubima/magazine.rubyist.net/discussions/categories/ideas にてアイデアをお知らせください

### 4. 記事のtypoを見つけたので知らせたい

* https://github.com/rubima/magazine.rubyist.net/discussions or https://github.com/rubima/magazine.rubyist.net/issues （#383 次第）にて該当箇所をお知らせください。Pull Requestの形でいただけるとより助かります

### 5. 記事の問題（技術的な誤りなど）を見つけたので知らせたい

* https://github.com/rubima/magazine.rubyist.net/discussions or https://github.com/rubima/magazine.rubyist.net/issues （#383 次第）にて該当箇所をお知らせください。

どうすかねえ? （💭  先に #383 をやった方が良さそうかな）

これが目に入った方：ユースケースでこぼしていそうなところがあったり、案内について「こうじゃない？」みたいなのがあれば、ツッコミもらえるとありがたいです  🙏

**Comment by snoozer05** [comment]
上をdiscussionsを使う形に直して、CONTRIBUTING.mdに反映する
