### ISSUE TITLE
コミュニケーションポイントを整理したい

### ISSUE THREAD

**Issue by takkanm** [rubima/magazine.rubyist.net#383]
[CONTRIBUTING](https://github.com/rubima/magazine.rubyist.net/blob/master/CONTRIBUTING.md) に以下のように書かれていますが、typo 指摘などは issues や直接PRをなげてもらったほうがいいのではと思っています。

```
ここはるびま編集部向けのイシュートラッカーです。

記事の typo 指摘や、るびまへの要望などは https://github.com/rubima/magazine.rubyist.net/discussions に登録をお願いします。
```

**Comment by snoozer05** [comment]
外の人が何かを書く際に「こっちはdiscussionsでこっちはissuesで」と使い分けなくてはならないのは負荷が大きいように思うので、一律discussionsに口があるか、全部issuesでやるかの方が良いようにも思います（PR投げてもらえる人はomakase）が、どうですかねぃ

**Comment by takkanm** [comment]
「一律discussions」を口にしたときの気になるポイント

 * 明確な close 条件があるものが New disscussion として作られた時、完了しても close できない
   * 「Lock conversation」があるが、本当にそれ？
 * トリアージ、issue 作成等が発生するが、たぶんそれをやるのは編集部の人になるのでコストがあがる
 * 一方、例えば「X号の感想」や「こういう記事が読みたい」みたいな disscussion をたてて読者とやりとりするのは向いていそう

「一律discussions」を口にしたときの気になるポイント

* Close 条件の明確でない意思表明場合にトリアージにこまりそう

このリポジトリまで到達するような人は、半数はソフトウェア開発をしたことがある人だと思いますし、使い分け方とフォールバックは disscussion でみたいなのがあれば、いい感じにできるんじゃないかとは思います。

**Comment by hsbt** [comment]
> 明確な close 条件があるものが New disscussion として作られた時、完了しても close できない
> * 「Lock conversation」があるが、本当にそれ？

https://github.blog/changelog/2023-03-14-adding-the-ability-to-close-github-discussions/

この前 close できるようになりました。なお convert issue もできます。

**Comment by snoozer05** [comment]
@hsbt 便利情報ありがとうございます！

@takkanm  

> 明確な close 条件があるものが New disscussion として作られた時、完了しても close できない

→これはできるとのことです

> トリアージ、issue 作成等が発生するが、たぶんそれをやるのは編集部の人になるのでコストがあがる

issue化も簡単にできるとのことです。トリアージはissueだろうがdiscussionsだろうが発生すると思っている「やる」となったことだけをissue化した方がトリアージもしやすいんじゃないかと思いましたが、何か受け止め方が違っているところありますかねえ

> Close 条件の明確でない意思表明場合にトリアージにこまりそう

これはよくわからなかったので、もう少し教えてもらえますか？ どう困るのかというのと、issueの場合と何が違うのかというのがよくわかっていないです...!!

**Comment by hsbt** [comment]
discussion でいいんじゃね?派なんですが、 ruby-build だと https://github.com/rbenv/ruby-build/issues/new/choose みたいに issue create のところで結構リッチな誘導をしています。この辺を copy して手直しでどうでしょうかねえ

**Comment by takkanm** [comment]
なるほど。いろいろありがとうございます。一度お互い不明瞭なところ同期しちゃった方が早い気がしてきましたが、どこかで10分程度syncしませんか？

**Comment by snoozer05** [comment]
了解です。Rubyの会のDiscord（の音声チャット）でやると良いかな。Discord の #rubima でタイミングについて声かけてもらえたらと思います

**Comment by kakutani** [comment]
+1 for Discussion。「閉じれる、Issueに変換できる」なら入口はDiscussionにして、 @snoozer05 の"「やる」となったことだけをissue化"するのがわかりやすそう、と思いました。

**Comment by snoozer05** [comment]
discussionsのカテゴリーを整理した上で、discussionsではじめてみる。運用してみて混乱があれば調整する。
このissueはdiscussionsのカテゴリーを整理したので、一旦閉じる。
