### ISSUE TITLE
READMEを整理したい

### ISSUE THREAD

**Issue by snoozer05** [rubima/magazine.rubyist.net#388]
るびまの各種リポジトリを統合したので、るびまの活動全体が捉えられるような形に見直したい

**Comment by snoozer05** [comment]
案を考えてみます

**Comment by snoozer05** [comment]
コンテキスト:

- 元々は役割ごとにリポジトリが分かれていた
   - https://github.com/rubima/rubima: 進行管理
   - https://github.com/rubima/rubima-support: 読者とのやりとり
   - https://github.com/rubima/magazine.rubyist.net: るびまのコード
- 運営を軽量にするため、もろもろ整理してこれを本リポジトリに集約した

解決したいこと:

- 本リポジトリのREADMEがるびまのコードだけを管理していたときのもののままとなっており、現状に即していない。ので、これを「るびま」という活動全体を説明するようなREADMEに更新したい

どうすると良いか:

- 今のREADMEにある内容は、記事執筆者向け、編集者向けと整理してdocの下に移す
- るびまに興味を持ってリポジトリにきてくれた人に以下を説明するREADMEに更新する
   - るびまとは
   - るびまにコントリビュートしたい場合は（CONTRIBUTING.mdへの導線）
   - るびまを手元で動かしたい場合は（上記で移したdocへの導線）

こんな感じかなあ

**Comment by kakutani** [comment]
よさそう。

> * 今のREADMEにある内容は、記事執筆者向け、編集者向けと整理してdocの下に移す

すでに`editing_`があるから`writing_`みたいな感じにできそうですね。
