### ISSUE TITLE
編集コミュニティへの導線を整える？

### ISSUE THREAD

**Issue by snoozer05** [rubima/magazine.rubyist.net#396]
https://github.com/rubima/magazine.rubyist.net/issues/359#issuecomment-1510520459 から切り出し

新しい人に編集コミュニティに来てほしいけれども、来てもらえるような導線が整っていたかどうか。
現状どんなふうになっていたかをおさらいし、その上で、見直せるところがあるなら見直す

**Comment by neko314** [comment]
常に見えているところにもリンクがあっても良いかなあと思いました。

FAQにはリンクを追加していただく（とても良いと思いました〜✨）のと、今でも各号の表紙のページには下部に「連絡先：[るびま編集部](mailto:magazine@ruby-no-kai.org)、[るびまサポート](https://github.com/rubima/magazine.rubyist.net/discussions)」のような記載がありますが、各記事中にはありません。

例えば、「編集部に加わりたい」まで行かなくても、記事を読んでいて「typoを見つけたのでPRを出したい」等のライトな動機を持った場合に、今だと「まずどうすればいいかどこに書いてあるか探す（その結果各号の表紙やFAQにたどり着く...）」という行為が発生しそう。その手間を省いて、このリポジトリに（今よりもうちょっとだけ）辿りつきやすくなっているのも、動線整理の一環に良さそうに思いました！

アイディアとしては、サイドバーの下部にリンクを置く、とか💭

**Comment by snoozer05** [comment]
コメントありがとうございます！
号の扉よりも各記事を読んでいるところに動線があった方が確かに良さそうですね！いただいたアイデア含めて、ちょっと考えてみようと思いますー

**Comment by snoozer05** [comment]
一旦はこんな感じかなあというところまではやれたと思うので閉じます
