### ISSUE TITLE
画像が表示されない #0018

### ISSUE THREAD

**Issue by topstone** [rubima/magazine.rubyist.net#427]
[第18号「Ruby/SDLで始めるゲームプログラミング【前編】」](https://magazine.rubyist.net/articles/0018/0018-GameProgramingForRubySDL.html)で、

`新しいウィンドウが開いて、2 秒後に閉じれば成功です。Ruby/SDL の世界へようこそ！`

の後に画像があるべきと思われますが、表示されません。

修正方法が分からず pull request を作れないので、issue として書かせていただきます。

**Comment by hsbt** [comment]
雑にファイルをリネームが良さそうですね。

**Comment by znz** [comment]
確認していないですが `_` をエスケープして `\_` にするだけで直るかもしれません。

**Comment by neko314** [comment]
リネームで表示されるようにしました🍎
