### ISSUE TITLE
0063号

### ISSUE THREAD

**Issue by kakutani** [rubima/magazine.rubyist.net#428]
## 0063号に向けて公開済の記事

* [KeebKaigi 2023 準公式参加記録](https://magazine.rubyist.net/articles/0063/0063-KeebKaigi2023Report.html) (2023-06-17)
* [プログラミング言語 Ruby30 周年記念イベント レポート](https://magazine.rubyist.net/articles/0063/0063-ruby30thReport.html)(2023-06-20)
* [Rails Girls Tokyo 15th 開催レポート](https://magazine.rubyist.net/articles/0063/0063-RailsGirlsTokyo15thReport.html) (2023-06-21)
* [Rails Girls Kagoshima 2nd 開催レポート](https://magazine.rubyist.net/articles/0063/0063-RailsGirlsKagoshima2ndReport)(2023-10-17)

## 0063号リリース時期に見通し

0063号としてのリリースは、9月までには出せるといいかなあと考えています。
(9月以降は地域Ruby会議やカンファレンスも活発になるのでその前にflushできるとよさそう)

##  0063号リリースに向けて決まったこと

- [x] どこで0063号とするのかを決める
- [x] 巻頭言を依頼する
- [x] (記事が揃ったら)表紙をつくる([0062でのつくりかた](https://github.com/rubima/magazine.rubyist.net/issues/428#issuecomment-1586166783)
(TODO: リリースのアナウンス - 0062のを参考に)

```[tasklist]
### 0063号に含める予定の記事
* [ ] #385
* [ ] #431
* [ ] #432 
* [ ] #425 
* [ ] #439
* [ ] #457
* [ ] #449
* [ ] #458
* [ ] #436 
* [ ] #435 
* [ ] #451 
```

```[tasklist]
### Best Effortで何卒… 🙏 
* [ ] #430 
* [ ] YARV Maniacs (@ko1) -- https://github.com/rubima/magazine.rubyist.net/issues/353#issuecomment-1512093784
* [ ] #445 
```

* * *

## Issueをオープンしたときの気持ち

#353 のときに「次号は2023年内ぐらいに出したい」との @takkanm の記述をどこかで見かけた気がした(のだけれども、見つけられず)のですが、RubyKaigi 2023 の #kaigieffect が手応えてきにいい感じなので、0063号のリリースに向けて進めていきたい。

言い出しっぺが進行係になる…となれば私がやるのかな…大丈夫かしら。リリースは「完成」があるからDiscussionじゃなくてIssueでよいでしょうか。

## リリース方法(の提案)
(これは個別にDiscussionにしたほうがいいのかな? → した #434 )

旧来の方式——リリース日までに公開Readyな記事を集めて、巻頭言・編集後記などの体裁を整えて「リリース」をアナウンスする、というかたちではなく、Continuous Delivery(CD)にしたいです。

なぜなら:

* リリース日めがけて、複数の記事を「完成」させていくのは作業量や担当者の負荷も高いため、できるだけ「1個流し」にしたい
* るびまの「号」としての価値は、後日参照する(何年も経ってからだったりする)ときに、便利な概念だと思います

だからです。これを踏まえると:

* 「CDにする」とは具体的には、1記事ずつ「完成」したらmasterにマージして、記事単体で「公開」とする
* ある時期がきたら、リリースタグのようなかたちで巻頭言と編集後記をmasterにマージして、それを特定の号のリリースとする
  * 各方面には、このときに「ある号が出た」とアナウンスする
  * ある号に含まれる記事は、その前の号から今回の号までに「公開」された記事とする

## コンテンツ観点から、RubyKaigi 2023関連記事がほしい
(これも個別にDiscussionにしたほうがいいかな? → こっちはIssueにしてみる #435 )

やはり日本Rubyの会の目玉イベントのRubyKaigiの記事がるびまにないのは寂しい…。
とはいえ、基調講演やトークのレポートはたいへん。でもなんか記事がほしい。
それも、るびまにしかできないやつ。

たとえば、基調講演やトークのスピーカー(LTもかな)から、今年のRubyKaigi 2023や松本の感想を
1〜2 tweetぶんぐらいの文章・メッセージを寄せ書き的に集めるのはどうでしょう。

* 書いてもらえた人のぶんをまとめておく(感想文をもらうには一定期間の締め切りを設けて、回収はBest Effortとする)
* 内容は体裁を整えることを中心。typoやるびまLintにだけ対応する(これなら編集の手間を中心に作業できそう)。
* 英語でEnglish Speakerからの感想文は翻訳しない。
* メッセージを集めるのはGoogle Formでいいんじゃない?

WDYT? @takkanm (にメンションしますが、どなた様からもコメントを歓迎します!

**Comment by hsbt** [comment]
https://github.com/rubima/magazine.rubyist.net/discussions/404 @joker1007 も記事候補によさそうです。

**Comment by kakutani** [comment]
> #404 @joker1007 も記事候補によさそうです。

おお…ありがとうございます! 技術記事ありがたい! convert to issueの練習してみよう。

**Comment by kakutani** [comment]
リリース対象の記事はlabelをつけるのではなく、milestoneに割り当てるのがよさそう

**Comment by hsbt** [comment]
>リリース方法(の提案)

基本よさそう、って感じました。一つ気になるのは tag を打つ基準でした。高橋さんの巻頭言が欲しくなったら打つ、みたいな感じ...? となると欲しくなるのはいつ、みたいなループになりそう。

* 四半期とか、半期ごと
* 記事が5つとか8つ溜まったら

とかその辺を合意しておくといいかも。

**Comment by kakutani** [comment]
> 四半期とか、半期ごと

四半期だと春夏秋冬で @takahashim の巻頭言が読めてよさそうw

> 記事が5つとか8つ溜まったら

マージされた記事の様子をうかがって、「そろそろ欲しいな…」みたいな時期にお願いするとよさそう

この話題は継続審議な気がする〜 (Discussionにもっていけるとよさそう)

**Comment by hsbt** [comment]
めちゃくちゃ雑なんですが RubyKaigi と RubyWorld Conf の後、とかにしてしまうとやっていきの高まり具合でやりやすいのかもしれない。

**Comment by kakutani** [comment]
#425 のackがもらえたので、descの記事候補に追加した。

**Comment by kakutani** [comment]
#431 のDraft PRをopenした!

**Comment by kakutani** [comment]
> リリース方法(の提案)

⏭️ #428

**Comment by kakutani** [comment]
> コンテンツ観点から、RubyKaigi 2023関連記事がほしい

⏭️ #435

**Comment by kakutani** [comment]
#431 をマージして単発で公開しちゃおっかな、と思ったのですが、0063の号トビラが存在していないと記事に辿りつくのが困難だな、と思ったので「0063(WIP)」みたいな仮の号トビラをつくっておくといいのかな、と思いました。

号トビラの作りかたのヒントってどこかに書いてあったりします?? @takkanm

**Comment by takkanm** [comment]
> #431 をマージして単発で公開しちゃおっかな、と思ったのですが、0063の号トビラが存在していないと記事に辿りつくのが困難だな、と思ったので「0063(WIP)」みたいな仮の号トビラをつくっておくといいのかな、と思いました。
> 
> 号トビラの作りかたのヒントってどこかに書いてあったりします?? @takkanm

前号のときに、記事がそろった後に作るスクリプトを用意して、それを使っていました。

> $ ruby editing_tools/generate_index_and_editors_note.rb  0062 2023-04-30 

https://github.com/rubima/magazine.rubyist.net/blob/5ba1118d11beedede14a51f0c4146f017c7920c0/editing_tools/generate_index_and_editors_note.rb

ただ作り的には今のままだと、追記型には使えません。

また、表紙を merge してしまうと、https://magazine.rubyist.net/ の最新号とかのリンクが書き換わる仕組みになっていたはずなので、これも今のままだと嬉しい動きではないと思います。

個人的には、単発の記事の公開については、この Issue に個別記事へのリンク集を用意しておくだけで、サイトトップからのリンクはなくオーファンなページでもいいのではと思っています。

**Comment by kakutani** [comment]
表紙情報ありがとうございます。

> 個人的には、単発の記事の公開については、この Issue に個別記事へのリンク集を用意しておくだけで、サイトトップからのリンクはなくオーファンなページでもいいのではと思っています。

なるほど。ワークフローが定まってないのに自動化してもアレなんで、こんかいはこれでいこうと思います!

**Comment by kakutani** [comment]
記事1個流し実験第1弾として [KeebKaigi 2023 準公式参加記録](https://magazine.rubyist.net/articles/0063/0063-KeebKaigi2023Report.html) を公開しちゃいました(Descriptionに反映済)

**Comment by kakutani** [comment]
#385 を [プログラミング言語 Ruby30 周年記念イベント レポート](https://magazine.rubyist.net/articles/0063/0063-ruby30thReport.html) として公開済みにしました(Descriptionに反映済)。超大作おつかれさまでした! @neko314

**Comment by kakutani** [comment]
@ericgpks るびまプロダクションにデプロイされました! [Rails Girls Tokyo 15th 開催レポート](https://magazine.rubyist.net/articles/0063/0063-RailsGirlsTokyo15thReport.html) twitterとかでshout-outしてもらえれば〜! (おつかれさまでした!; Description反映済)

**Comment by neko314** [comment]
@takkanm @kakutani 
記事PRが新規で作成されたり溜まったりしているのを公開していけたらというのと0063号全体を少しずつでも前に進めて行けたらと思ってコメントします。
> 0063号としてのリリースは、9月までには出せるといいかなあと考えています。

は当初良さそうと思っていたのですが、なんと10月!というような暦も鑑みて、個人的な考えですが、このようにやっていくのはどうだろうかと思っています。いかがでしょうか。

- 2023年内に公開できた記事を0063号とする
  - 2023/10/01の時点でこのissueの「0063号に含める予定の記事」にない記事のPRを作っていただいているものも一律0063号に含める
  - 今年の秋の各地で盛りだくさんのカンファレンス関係の記事を書いてくださる方がいる場合も0063号とする
  - 0063号の表紙作成は、11月・12月頃に誰かがやる（少なくとも私ができます🙂）
    - その時期を目安にして巻頭言を書いていただけるようにお願いする
    

このような感じでよければ、Hotlinksも11月末ごろまでに公開できると良さそうかな等と思い巡らせています（記事を書いてくださる皆様の無理のない範囲で、ですが）。

迷っていることはRubyKaigiの記事はできたらいいが、時季を逃してしまったかしら、どうするのが良いだろうかというあたりです。https://github.com/rubima/magazine.rubyist.net/issues/435 の方法で、今から数名でも登壇者等からメッセージをいただけそうならやってみるのは良いかも。一回やってみると記事を充実させるための段取りも見えてきて、来年に繋げることができるような気もします。


上記はあくまで個人の考えですが、無理なくやっていける良い感じの方針を決めれたらなーと思っています。


私自身は、今まで数ヶ月無活動だったのですが、今後ゆるゆるとながらコンスタントに活動していける・いくつもりです🙏
で、手始め（?）に最近新しく作成いただいたhttps://github.com/rubima/magazine.rubyist.net/issues/456 や https://github.com/rubima/magazine.rubyist.net/pull/458 はレビューしたりマージして公開まで持っていけるようにしたいと考えています〜🙂

**Comment by neko314** [comment]
@takkanm 
OKです〜

**Comment by snoozer05** [comment]
@neko314 cc @takkanm 
リリース大変お疲れ様です！Xのアカウント情報、島田が知っているのは古いものみたいでした...
他の理事に確認してみます！

**Comment by neko314** [comment]
@snoozer05 

なんと...
よろしくお願いします！ありがとうございます。

**Comment by snoozer05** [comment]
パスワード取得できましたので、しまだの方で以下の通りポストおきました！

https://twitter.com/rubynokai/status/1744909063539073527

**Comment by neko314** [comment]
@snoozer05 

ありがとうございました✨

---

アナウンスまで完了したので、このissueはcloseします🙏
