### ISSUE TITLE
Rubyist Hotlinks(39): 古橋貞之さん

### ISSUE THREAD

**Issue by kakutani** [rubima/magazine.rubyist.net#436]
### 状況まとめ

* [x] インタビューデータその1(松本収録分)
* [ ] 松本収録分文字起こし (@snoozer05 がやってくれている)
  * "6月中には、他の人にチェックをお願いできる状態までは持っていけるかなーと思っています" #ﾄﾉｺﾄ
* [ ] 松本収録は時間切れで中途半端に終わっているので続きをどうするか決める( @takkanm)
* [ ] 原稿をどこで共有するか決める
  * [ ] インタビューの文字起こしはそのままｲﾝﾀｰﾈｯﾂに出るとよくないケースもありそうなので、適切な方法を編み出したい
* [ ] マージまでにやることをリストアップする(メタタスク)
* [ ] マージしたらclose

**Comment by kakutani** [comment]
0063に収録するかどうかは考えていない

**Comment by takkanm** [comment]
> [x] インタビュー収録済

収録状況としては、一旦時間切れで中途半端に終わっているので、それをどうするかという課題あり

**Comment by kakutani** [comment]
> 収録状況としては、一旦時間切れで中途半端に終わっているので、それをどうするかという課題あり > ボールは takkanm 持ち

descriptionに反映させました!

**Comment by kakutani** [comment]
0063号はRubyist Hotlinksか技術記事がある号にしたい! という気持ちをここにダンプします( #428 の含めたい記事のリストに追加した)

**Comment by snoozer05** [comment]
進行状況の報告です。
毎日ちょっとずつ文字起こしして、ようやく１周、文字起こしを完走しました。
この後、通しで聴きながら手直しという作業を１周か２周したものをドラフトとして、何かかしらの手段で関係者に共有しようと思います。見通しとしては、再来週（7/10の週）を目指しますー

**Comment by takkanm** [comment]
@snoozer05 お疲れ様です。対応、ありがとうございます。
現状のファイルを Google Docs など限られた複数人で確認や編集をできるところに置くのは難しいでしょうか？
参加者に内容確認や、時間切れになった終わりをどうするかとかを相談したいので。

**Comment by snoozer05** [comment]
はい、そのような共有手段を考えていました（Rubyの会のGoogle Driveに置いて限られた方のみにシェアしようかなと考えています）

**Comment by hsbt** [comment]
https://magazine.rubyist.net/articles/0064/0064-Hotlinks.html として公開しました。64号としての目次発行までに修正点があれば都度 pull-request 作成などでお願いします。
