### ISSUE TITLE
RailsGirls の開催レポートを分野別目次にまとまるようにしたい

### ISSUE THREAD

**Issue by takkanm** [rubima/magazine.rubyist.net#445]
現在、以下の RailsGrils の開催レポートが存在していますが、分野別目次にはでていないようです。これらを地域 Ruby 会議のように分野別目次にのるようにしたいです。

```
./articles/0059/_posts/2019-01-27-0059-RailsGirlsTokyo10th.md
./articles/0059/_posts/2019-01-27-0059-RailsGirlsSendai1stReport.md
./articles/0060/_posts/2019-08-18-0060-RailsGirlsSendai2ndReport.md
./articles/0060/_posts/2019-08-18-0060-RailsGirlsTokyo12th.md
./articles/0060/_posts/2019-08-18-0060-RailsGirlsNagano1stReport.md
./articles/0062/_posts/2023-04-30-0062-RailsGirlsTokyo14thReport.md
./articles/0054/_posts/2016-08-21-0054-RailsGirlsTokyo6thReport.md
```

ステップとしては、

1. 各記事の tag に `RailsGirlsReport` を追加する
2. [分野別目次のファイル](https://github.com/rubima/magazine.rubyist.net/blob/5ba1118d11beedede14a51f0c4146f017c7920c0/articles/backnumber/_posts/2000-01-01-backnumber.md) に `RailsGirlsReport` がのるようにする

**Comment by ericgpks** [comment]
このissueやりたいです！

**Comment by takkanm** [comment]
@ericgpks お願いします！！
