### ISSUE TITLE
RedAmberのドキュメントを整備する際に見つけたYARDのtips

### ISSUE THREAD

**Issue by heronshoes** [rubima/magazine.rubyist.net#448]
こんにちは。Rubyで書かれたデータフレームライブラリ RedAmber を作っている @heronshoes と申します。
RubyKaigi2023では　3日目の午前中に RedAmberについて発表させていただきました。
https://rubykaigi.org/2023/presentations/heronshoes.html

早速ですが、るびまに載せていただけたらいいなー、という記事のネタがあるので提案させていただきます。
RedAmberのドキュメントをYARDで書くにあたって工夫した点2つについてです。とは言ってもRedAmber固有のものではなく、
Rubyで書いたコードにYARDでドキュメントをつける場合に役立つかもしれないTipsです。

 1. 動的に生成したメソッドに対してYARDをつける方法
 2. YARDでカスタムcssを読み込ませて、コード部分のフォントを変更する方法

[RedAmberのドキュメントを整備する際に見つけたYARDのtips](https://gist.github.com/heronshoes/b67d54eaab2f49ec836cc82fc8bf206c)

どちらも、2022年の Ruby Association Grant の報告書の一部として書いたものですが、
成果報告がまだなので報告書はまだ公開していません。
この部分は独立して広く公開した方がいいと思うのでるびまに載せていただいたらどうかと考えました。

どちらもドキュメントをよく読めばやり方に辿り着けるかもしれないのですが、具体的な事例として示されているものが
無かったので、こういう記事があってもいいのではないかと思いました。

Red Data Toolsで共有した時には、YARDに成果を還元したらどうかとアドバイスをいただきましたが、
使用例なのでcontributeする良い場所を見つけられず、それならばここで提案しようと思った次第です。

るびまで使っていただけるのであれば、背景説明などを加筆・修正しようと思います。
如何でしょうか。

**Comment by kakutani** [comment]
@heronshoes RubyKaigiおつかれさまでした。るびまの記事執筆に興味を持ってもらえてうれしいです! ぜひよろしくお願いします。

> 使用例なのでcontributeする良い場所を見つけられず、それならばここで提案しようと思った次第です。

これは素朴な疑問なのですが、「5.2 YARDドキュメントでコード部分に等幅フォントを指定する方法」は確かに「使用例」ではあるのですが、`@example`ってコード例が出てくるものだろうからデフォルトが等幅フォントになってたほうが使い勝手はよいのでは? という感想を抱いたのですが、そうもいかないんですかねえ。

**Comment by heronshoes** [comment]
ありがとうございます。進めてみます。

5.2についてはデフォルトに反映させるのが一番いいと私も思うんですが、どこに反映すべきかよくわかっていないんです。yardocのサイトではmonospaceフォントが設定されていて問題ないようなので、ローカルで表示させるときの問題で本当に誰も問題視していないのかよくわかってないので、もう少し考えてみます。
