### ISSUE TITLE
neko314 さんを編集部に招待したい

### ISSUE THREAD

**Issue by takkanm** [rubima/magazine.rubyist.net#450]
Ruby30 周年の記事を書いてくれた @neko314 さんがるびまの編集としてのコントリビューションに興味があるようなので、編集部に招待したいです。
事後報告になりますが、すでに rubima リポジトリに招待しています。

**Comment by neko314** [comment]
招待ありがとうございます✨

**Comment by kakutani** [comment]
パワーを得たらcloseしてください! @neko314

**Comment by neko314** [comment]
マージできるパワーをいただいたのでcloseします🫡
