### ISSUE TITLE
Rails Girls Kagoshima 2nd 開催レポート

### ISSUE THREAD

**Issue by hayasaki-shunsuke** [rubima/magazine.rubyist.net#456]
Rails Girls Kagoshima 2ndの開催レポートを寄稿します。

レポート担当 : @hayasaki-shunsuke
イベントページ: https://railsgirls.com/kagoshima-2023.html
開催日: 2023/9/1 ~2
記事作成締切: 2023/9/30

0063号リリースの話が動いていると思いますが、間に合わなければ別のタイミングでリリースしていただけるとありがたいです🙏

**Comment by hayasaki-shunsuke** [comment]
@kakutani 
GMOペパボの早崎です。
0063号 https://github.com/rubima/magazine.rubyist.net/issues/428 のやりとりを拝見しております。
Rails Girls Kagoshima 2ndを開催したのでレポートを作成しました。 https://github.com/rubima/magazine.rubyist.net/pull/457

レビューと0063号への掲載の御検討をよろしくお願いします！

**Comment by neko314** [comment]
@hayasaki-shunsuke 
こちらで特にお返事書いておりませんでした🙏
63号に入れますね🫡

**Comment by neko314** [comment]
@hayasaki-shunsuke 
公開しました

URLはこちらです💁‍♀️ https://magazine.rubyist.net/articles/0063/0063-RailsGirlsKagoshima2ndReport

こちらのissueはクローズします👍
