### ISSUE TITLE
Rails Girls Matsue 5th 開催レポート

### ISSUE THREAD

**Issue by ishikawa999** [rubima/magazine.rubyist.net#463]
2023/11/11に島根県松江市で開催したRails Girls Matsue 5thのレポートを記事を書きたいです。
RailsGirlsの方でもレポートを作成中なので、これをベースにRails Girlsについての説明などを加えて書ければよいかなと思っています。 https://github.com/railsgirls-jp/railsgirls.jp/pull/762

イベントページ: https://railsgirls.com/matsue-5th
開催日: 2023/11/11
執筆者: 槇原 育美さん( @ama3193 )
（るびま掲載に合わせての追記やフィードバック対応は私 @ishikawa999  が行う予定）

**Comment by ishikawa999** [comment]
https://github.com/rubima/magazine.rubyist.net/blob/master/doc/writing_process.md を見ているのですが、
> ファイル名にあるyyyymmddの部分は、号数のリリース予定日です。これはるびま編集部が決めます。

の部分はどうすれば良いでしょうか？

**Comment by neko314** [comment]
@ishikawa999 
> > 記事は、articles/号数/_posts/yyyy-mm-dd-号数-記事名.mdとして作成してください。
画像ファイルなどはimages/号数-記事名以下に配置してください。
ファイル名にあるyyyymmddの部分は、号数のリリース予定日です。これはるびま編集部が決めます。
> の部分はどうすれば良いでしょうか？

その内容更新しないとですね。それは別途こちらでやるとして...。
最近の記事は、個別にマージしていて、マージしたら記事が公開されるようになっています。完璧に手順化しているわけではないのですが、ひとまずブランチ切ったりPR作ったりした日付にしておいていただいて、マージするタイミングでに日付を更新するパターンが多いです。書いていただく記事もそのようにしていただくのが良いかなと思います。

**Comment by ishikawa999** [comment]
@neko314 
ありがとうございます。そのようにします 🙇

**Comment by neko314** [comment]
@ishikawa999 
こちらお知らせできてなくてごめんなさい！
号として完成していなくても個別の記事1つ1つで公開していくスタイルになっております。
書いていただいた記事はこちらのURLで公開ずみです！
書いてくださりありがとうございました✨
https://magazine.rubyist.net/articles/0064/0064-RailsGirlsMatsue5thReport.html
