### ISSUE TITLE
0064号 RubyKaigi 2024のフォトレポート用の写真募集

### ISSUE THREAD

**Issue by neko314** [rubima/magazine.rubyist.net#500]
## やりたいこと

#491 で述べたように、RubyKaigi 2024の様子を残せるような記事を作りたいです。今回はフォトレポート形式の記事を作り0064号に掲載します。そのための写真を募集します。

## 募集内容

お手元にあるいい感じの写真を送っていただきたいです。
いい感じな写真とは、基本的には感性にお任せなのですが
- RubyFriendsな写真
- 例えば突発的に発生した議論の様子や、偶然な一瞬を捉えた写真
- 一目でRubyKaigi 2024だなとわかるような特徴的な写真

などです。

オフィシャルにLovegraphさんによるフォトスポンサーがあったことにより、登壇中のスピーカーの写真などはそちらに良いものがたくさんあるようなので、アンオフィシャルな一幕の写真をメインにできるとよさそうだと考えています。

## 応募方法

以下のフォーマットでこのissueにコメントをください。

```
撮影した人: 名前 or ID
何日目か:  会期前 | Day1 | Day2 | Day3 | 会期後
ひとこと: 任意で何かあれば短めに
画像の URL or 画像そのもの
```

## 募集期間

2024/06/30(日)まで

## ご留意いただきたいこと
- 撮影者本人による応募に限ります
- [RubyKaigiのポリシー](https://rubykaigi.org/2024/policies/)を遵守してください
- [オンサイトインフォメーション](https://rubykaigi.org/2024/onsite/)にある通り、白いストラップをつけた人が写真に写っていないか確認してください
- 関係者ではない人がはっきり映り込んでいるような場合はマスクするなどの処理をお願いします。例えば街中で撮った写真の背景に通りがかりの人の顔が写っているようなケースです。
- 最終的に応募いただいた写真を掲載するかどうかは編集部で決定します
- 必要に応じて、編集部で画像のリサイズなどの処理を行います
- 掲載した写真は[るびまライセンス](https://github.com/rubima/magazine.rubyist.net/blob/6ca34ef0cabe6a3ade0587777d30e883af91b651/license.md)に帰属します

皆様どうぞよろしくお願いします。

**Comment by neko314** [comment]
## サンプル
下記のコメントをもらった場合、このように掲載するイメージです。

### コメント例


撮影した人: neko314
何日目か:  Day1
ひとこと: [玉城豆腐のみそ汁屋](https://www.instagram.com/tamakidoufuno_misoshiru/)でランチ
![1000005016](https://github.com/rubima/magazine.rubyist.net/assets/29836309/030f67bb-c8c8-4404-ae69-58d02501d5da)

### 記事の仕上がりイメージ

![CleanShot 2024-06-08 at 10 32 39](https://github.com/rubima/magazine.rubyist.net/assets/29836309/bc6ba1b7-7d56-406c-a9d7-ce43928a82ae)

**Comment by shioimm** [comment]
誰かがもっといい角度から撮影されているかもしれませんが…

撮影した人: しおい (coe401_)
何日目か: Day3
ひとこと: Ruby Committers and the Worldにて、Rubyコミッター大集合
https://pbs.twimg.com/media/GNv6xO0aoAAlX2Y?format=jpg&name=large

**Comment by ima1zumi** [comment]
撮影した人: しおいさんがima1zumiのiPhoneで撮ってくれた
何日目か:  Day3
ひとこと: After PartyでIRB Reline Teamが集合できた記念
![CFCE8FD4-D8AF-4138-A6C7-BAB4EE349A26_1_105_c](https://github.com/rubima/magazine.rubyist.net/assets/52617472/8edae5d1-6eee-46ee-abc3-7f1279e8aea2)

**Comment by ujihisa** [comment]
自由に使ってください!

撮影した人: ujihisa
何日目か:  Day1

10:57am
![image](https://github.com/rubima/magazine.rubyist.net/assets/11504/e686ceb0-0584-4895-aede-f3f30b5fa4cb)

1:32pm
![image](https://github.com/rubima/magazine.rubyist.net/assets/11504/300d57e4-bc91-43b9-ab06-e0444eef14e7)

6:50pm
![image](https://github.com/rubima/magazine.rubyist.net/assets/11504/a8e28317-cd88-4746-bc48-6f86ae123f5f)

**Comment by hayat01sh1da** [comment]
- 撮影者 = 投稿者: @hayat01sh1da
- 被写体がほぼ無生物ですがご容赦ください
- 現地でコロナに罹患してしまったので Day 2 以降の写真はありません
- ご自由にお使いください

人と写った写真が一枚もないことに気づきました(Day 1 でコロナになってしまい初日しか参加できなかったのもありまして)

## 1. Day 0

### 1-1. 空港お出迎え

![Ruby Kaigi 01](https://github.com/rubima/magazine.rubyist.net/assets/37478830/4f45254c-b2f9-47a1-8107-060df5b9a4ef)

### 1-2. 昼食 at 那覇市第一牧志公設市場

![Ruby Kaigi 02](https://github.com/rubima/magazine.rubyist.net/assets/37478830/c5bad108-b120-46f8-bc81-af63bb4a93f8)
![Ruby Kaigi 03](https://github.com/rubima/magazine.rubyist.net/assets/37478830/6af33248-3ad6-4e23-9524-4756ba98c57c)
![Ruby Kaigi 04](https://github.com/rubima/magazine.rubyist.net/assets/37478830/5384acef-d08f-48ae-ab27-5868e8cba59f)
![Ruby Kaigi 05](https://github.com/rubima/magazine.rubyist.net/assets/37478830/6f381827-4140-4855-8225-2c0efa793380)
![Ruby Kaigi 06](https://github.com/rubima/magazine.rubyist.net/assets/37478830/55646760-4759-457b-b791-2b705d9c37c0)

### 1-3. 首里城観光

![Ruby Kaigi 07](https://github.com/rubima/magazine.rubyist.net/assets/37478830/f56dcc5a-3e0f-431c-9ded-722cc69911c5)
![Ruby Kaigi 08](https://github.com/rubima/magazine.rubyist.net/assets/37478830/ea59fa46-555b-4605-8f94-036ffa760b43)
![Ruby Kaigi 09](https://github.com/rubima/magazine.rubyist.net/assets/37478830/302dea2c-632e-4ea1-8bc7-eba60a98a3bf)
![Ruby Kaigi 10](https://github.com/rubima/magazine.rubyist.net/assets/37478830/282b5077-65c8-4d97-86ab-1a8497bb9919)
![Ruby Kaigi 11](https://github.com/rubima/magazine.rubyist.net/assets/37478830/1f50905d-362f-4c22-ae25-fa9a8838db20)
![Ruby Kaigi 12](https://github.com/rubima/magazine.rubyist.net/assets/37478830/399d2b8f-e05c-4287-8c3b-2fa320afdf7d)
![Ruby Kaigi 13](https://github.com/rubima/magazine.rubyist.net/assets/37478830/1118a803-4933-42cb-b967-10f1cd59b1be)
![Ruby Kaigi 14](https://github.com/rubima/magazine.rubyist.net/assets/37478830/035f0033-687c-40a3-9d29-ec0580fc8f59)
![Ruby Kaigi 15](https://github.com/rubima/magazine.rubyist.net/assets/37478830/2a1212cf-f664-4996-a8c4-1e2af5136219)
![Ruby Kaigi 16](https://github.com/rubima/magazine.rubyist.net/assets/37478830/8bb5c6b7-7176-4583-8e40-0a1fe70bb24b)
![Ruby Kaigi 17](https://github.com/rubima/magazine.rubyist.net/assets/37478830/d8a4c8cd-6f7f-4590-b9ae-fc3f580a41f9)
![Ruby Kaigi 18](https://github.com/rubima/magazine.rubyist.net/assets/37478830/56163f35-ce8b-41c9-859d-0807e7390bb3)
![Ruby Kaigi 19](https://github.com/rubima/magazine.rubyist.net/assets/37478830/89f3f4b0-2956-40ea-b6ce-2f8e9efe1890)
![Ruby Kaigi 20](https://github.com/rubima/magazine.rubyist.net/assets/37478830/97a9e091-1935-4fb1-8c0f-c47367f0e9f9)
![Ruby Kaigi 21](https://github.com/rubima/magazine.rubyist.net/assets/37478830/588f1b19-62d1-4745-80b0-bccb0df7ebf9)

### 1-4. RubyKaigi 2024 前夜祭 Asakusa.rb Welcome Drinkup

![Ruby Kaigi 22](https://github.com/rubima/magazine.rubyist.net/assets/37478830/8fb4faf3-8f6e-48e1-b557-21b44d9cc556)
![Ruby Kaigi 23](https://github.com/rubima/magazine.rubyist.net/assets/37478830/757cbf16-e423-44e7-9303-be3769288c90)
![Ruby Kaigi 24](https://github.com/rubima/magazine.rubyist.net/assets/37478830/fd459d01-190c-4e7a-be62-4c1540db7d9f)
![Ruby Kaigi 25](https://github.com/rubima/magazine.rubyist.net/assets/37478830/51c1882e-a2bf-4a0c-9886-3ca9c2b6cc88)
![Ruby Kaigi 26](https://github.com/rubima/magazine.rubyist.net/assets/37478830/b2f6429f-4732-4088-b2c6-2f81709bd4ba)

## 2. Day 1

### 2-1. 会場

![Ruby Kaigi 27](https://github.com/rubima/magazine.rubyist.net/assets/37478830/4b894af8-e0b8-407b-a9a1-fab67062e1d9)
![Ruby Kaigi 29](https://github.com/rubima/magazine.rubyist.net/assets/37478830/8c773193-8f50-4782-812d-fc342388e2d4)
![Ruby Kaigi 30](https://github.com/rubima/magazine.rubyist.net/assets/37478830/87d3cf44-996f-4c59-8983-da3ad70e179a)

### 2-2. Official Party 道中

会場到着後急激に体調が悪化し即退場しましたので、撮影したのは一枚だけです。

![Ruby Kaigi 31](https://github.com/rubima/magazine.rubyist.net/assets/37478830/15016603-4238-4e17-be5c-8b92a35e0692)

**Comment by akinov** [comment]
よろしくお願いします！🙌

撮影した人: あっきー（kuronekopunk）
何日目か:  Day1
ひとこと: RubyKaigi 2024用のTシャツを作って参戦👍
![PXL_20240515_065236266](https://github.com/rubima/magazine.rubyist.net/assets/1765937/dded766b-c70e-46bb-99e7-bec225f6c0a5)


撮影した人: あっきー（kuronekopunk）
何日目か:  Day2
ひとこと: IVRyさんで電話になった
![PXL_20240516_092245871](https://github.com/rubima/magazine.rubyist.net/assets/1765937/97ffa456-94b4-4c68-a235-59161fd9d9ed)

撮影した人: あっきー（kuronekopunk）
何日目か:  Day3
ひとこと: After Party sponsored by mov 飲みまくってRubyを満たすぞ！
![PXL_20240517_092251391](https://github.com/rubima/magazine.rubyist.net/assets/1765937/ad4b2e77-a405-4404-bbfe-99ba595eb7b5)

撮影した人: あっきー（kuronekopunk）
何日目か:  Day3
ひとこと: After Party sponsored by mov！
![PXL_20240517_113829820](https://github.com/rubima/magazine.rubyist.net/assets/1765937/4f538cbd-759d-415d-91d5-dfb01e9a9155)

**Comment by neko314** [comment]
みなさんたくさんの素敵な写真ありがとうございます!!
ここまでのものは記事にコミット積みました。
めちゃくちゃいい感じなので、記事の公開をぜひ楽しみにしていてください😄

**Comment by jxmtst** [comment]
もう遅いかもしれませんがオフショットっぽいものがいくつかあったのでよろしければお使いください。

撮影した人: まつした(jxmtst)
何日目か:  Day2
ひとこと: スタンプラリー
![IMG_8803](https://github.com/rubima/magazine.rubyist.net/assets/46489765/bc6a81db-badc-4403-9542-9d21d78de21e)

何日目か:  Day2
ひとこと: RubyKaraoke
![IMG_8819](https://github.com/rubima/magazine.rubyist.net/assets/46489765/bf5d745b-4437-4f94-bbd8-c53415c9171f)

何日目か:  Day3
ひとこと: RubyMusicMixin
![IMG_8868](https://github.com/rubima/magazine.rubyist.net/assets/46489765/27fdb788-358b-4ec6-8ce5-b134bd27c05a)

**Comment by neko314** [comment]
@jxmtst 
> もう遅いかもしれませんが

まだまだ受け付けております！全く遅くないです！写真ありがとうございます😆

**Comment by shioimm** [comment]
追加しちゃお

撮影した人: しおい(coe401_)
何日目か: Day1
ひとこと: なはーと入り口、お出迎えをされる角谷さん
https://pbs.twimg.com/media/GNlQ73pbMAA-HAO?format=jpg&name=large

何日目か: Day1
ひとこと: Official Party会場 (波の上ビーチ) の夕景
https://pbs.twimg.com/media/GNnAx7DaUAA-aFI?format=jpg&name=large

何日目か: Day3
ひとこと: クロージングにて、RubyKaigi運営チームのMINASWAN。お疲れ様でした!
https://pbs.twimg.com/media/GNxO9MJbQAAWmfD?format=jpg&name=large

何日目か: Day4
ひとこと: RubyFriends with みんなが食べていた千日のぜんざい
https://pbs.twimg.com/media/GN6nldtaMAAu65R?format=jpg&name=large

**Comment by yasulab** [comment]
- 撮影した人: yasulab
- 何日目か: 会期後の松田さんによるトーク「たねあかし」にて
- ひとこと: RubyKaigi 2024 が沖縄に決まった瞬間?
- https://x.com/yasulab/status/1796505676594000318

![image](https://github.com/rubima/magazine.rubyist.net/assets/155807/f3947049-fb11-448e-a10e-203a54651ea2)

-----

- 撮影した人: yasulab
- 何日目か: Day 2
- ひとこと: 10年前からご一緒している Okinawa Friends
- https://x.com/yasulab/status/1790939560995910080/photo/1

![IMG_4298](https://github.com/rubima/magazine.rubyist.net/assets/155807/ce9286f8-ddd3-476e-89c0-51d7916bc176)

-----

- 撮影した人: hanachin
- 何日目か: Day 1
- ひとこと: 大倉さんと2人で飲んでたら続々と Rubyist と合流
- https://x.com/yasulab/status/1790787596278526201

![IMG_4291](https://github.com/rubima/magazine.rubyist.net/assets/155807/6b6db466-e489-4b04-aa03-80ff78ee9346)


-----

- 撮影した人: yasulab
- 何日目か: Day 1
- ひとこと: ゆんたくNight@RubyKaigi 2024 で唄っている様子
- https://x.com/yasulab/status/1790733913692008534/photo/1

![IMG_4284](https://github.com/rubima/magazine.rubyist.net/assets/155807/eaaf6dc3-d35c-414a-995f-64dea87021a8)

**Comment by moro** [comment]
塩井さんファンみたいになってしまいました。いや、そうなんですけど

撮影した人: @moro
何日目か:  Day1
ひとこと: 登壇直前の塩井さん
![IMG_0429](https://github.com/rubima/magazine.rubyist.net/assets/3419/e3ca1e7e-e157-488a-9b6e-238ce9858e3c)

撮影した人: @moro
何日目か:  Day1
ひとこと: Offical Partyの関さんと塩井さん
![IMG_0442](https://github.com/rubima/magazine.rubyist.net/assets/3419/85347b3b-e2c2-47e0-b408-3713e6a37ca6)


撮影した人: @moro
何日目か:  Day2
ひとこと: なんかカッコイイ那覇市役所
![IMG_0445](https://github.com/rubima/magazine.rubyist.net/assets/3419/4d30d3fb-7cb3-4db0-90c9-df88c6696871)

撮影した人: @moro
何日目か:  Day2
ひとこと: 弊社ブース付近に来てくれたがちゃぴん先生と塩井さん
![IMG_0451](https://github.com/rubima/magazine.rubyist.net/assets/3419/b346e69f-d8ad-4355-b9b1-6c384b57300f)

撮影した人: @moro
何日目か:  Day3
ひとこと:アイスを食べる島田さん
![IMG_0472](https://github.com/rubima/magazine.rubyist.net/assets/3419/2d837b26-72e2-459f-bcd1-25d7ad91e81c)

**Comment by Kiryuanzu** [comment]
撮影した人: @Kiryuanzu
何日目か: Day0 (ESMナイトクルーズのとき)
コメント: 会期前の写真なんですけど、みんな良い表情で写ってたのでつい共有してみました。チラッと写り込んでるふーがさんも好きなポイントです
![IMG_3137](https://github.com/rubima/magazine.rubyist.net/assets/23164048/fc401ada-edbc-4c07-a5e1-fc7ea2aec311)

**Comment by ynndino88** [comment]
@neko314 さん、写真募集のissueありがとうございます🙌 [discussion](https://github.com/rubima/magazine.rubyist.net/discussions/491)拝読しとっても共感しました！これからるびまを読んでくれる人にRubyKaigi2024の熱量や空気感が届きますように...💚

そして皆様、RubyKaigi2024おつかれ様でした🌊🌺✨素敵な写真ばかりですね〜！！！改めて余韻に浸っています😌
自分もめちゃめちゃ厳選したのですが、盛りだくさんになってしまいました🙏
（そして #RubyFriends な写真を推したくインカメ率が高めです🙈）
ちなみに[こちら](https://x.com/ynndino88/media)にあるRubyKaigiに関する投稿は全てSNS掲載許可いただいておりますのでもし以下に貼り付けていないものでもフォトレポートにご利用いただけるのであればぜひにです。

----------------------------------------

撮影した人: ヤノ | ROUTE06  @ynndino88
何日目か:  会期前
ひとこと: 空港のウェルカムボード前でのごきげん記念写真です🙈
https://github.com/rubima/magazine.rubyist.net/assets/69961886/e0d8d5f6-1791-4308-a372-81c42f815142

撮影した人: ヤノ | ROUTE06  @ynndino88
何日目か:  Day1
ひとこと: official partyのようす、WE ARE #RubyFriends!
![GNnRzAYbMAA994s](https://github.com/rubima/magazine.rubyist.net/assets/69961886/18fe760e-47a1-4787-8367-c3a714a577ab)
![GNnyqiKbEAApg11](https://github.com/rubima/magazine.rubyist.net/assets/69961886/e0cbb988-847a-4a3f-9783-1c3959aeeee8)

撮影した人: ヤノ | ROUTE06  @ynndino88
何日目か:  Day2
ひとこと: RubyKaigiといえばこの方々
![GNq_J9zaAAAddhm](https://github.com/rubima/magazine.rubyist.net/assets/69961886/aea96492-4de1-4df1-a668-862442296b06)
![GNrrdmBasAAuG08](https://github.com/rubima/magazine.rubyist.net/assets/69961886/691699b2-3472-4ba1-9f4d-31f1f54f1d42)

撮影した人: ヤノ | ROUTE06  @ynndino88
何日目か:  Day2
ひとこと: おやつタイム
![GNrqX2UaUAAMkPY](https://github.com/rubima/magazine.rubyist.net/assets/69961886/7d8c63f4-04a4-4eb7-8e6e-26d6638dea4f)

撮影した人: ヤノ | ROUTE06  @ynndino88
何日目か:  Day2
ひとこと: ずっと会いたかった人も、その場で初めましてな人も一緒に、#RubyFriends!
![GNrr9UGaMAAC_nx](https://github.com/rubima/magazine.rubyist.net/assets/69961886/71bca7a7-3627-4661-a80d-86ba308b9852)

撮影した人: ヤノ | ROUTE06  @ynndino88
何日目か:  Day2
ひとこと: ちゅらデータさんのドリンクアップでは沖縄らしく子豚の丸焼きが振る舞われました
![GNs4VyxbcAAJdf7](https://github.com/rubima/magazine.rubyist.net/assets/69961886/39a63883-abe0-4ed6-9257-f15babef6e34)

撮影した人: ヤノ | ROUTE06  @ynndino88
何日目か:  Day2
ひとこと:  RubyKaraoke で #RubyFriends!
![GNsxYFVa8AAoozN](https://github.com/rubima/magazine.rubyist.net/assets/69961886/37c716ef-3d50-408c-9cbd-6fb1627af9b2)

![GNtFDh_bgAA6Syo](https://github.com/rubima/magazine.rubyist.net/assets/69961886/44e460db-5a37-4456-809e-c2c0c8cf6414)
![GNs5Dz8bcAAyX2B](https://github.com/rubima/magazine.rubyist.net/assets/69961886/47cce200-c259-4ac8-8df4-85b909702cf6)

![GNuCwSzaAAEgrk6](https://github.com/rubima/magazine.rubyist.net/assets/69961886/7ce09efd-480b-4331-bbb9-5af240c894f5)
![GNuCwQ7aAAM4Fgb](https://github.com/rubima/magazine.rubyist.net/assets/69961886/95be113e-09ee-441f-9da6-9a3ae85c75d9)

撮影した人: ヤノ | ROUTE06  @ynndino88
何日目か:  Day3
ひとこと: 最終日も #RubyFriends!
![GNww79tbEAAfKxX](https://github.com/rubima/magazine.rubyist.net/assets/69961886/85609728-4933-428b-b8ba-6bf44aa54a2f)
![GNwK08pboAAhgWQ](https://github.com/rubima/magazine.rubyist.net/assets/69961886/1a3106c9-d00f-441c-8bc3-613f3084842b)
![GOAiH9sa4AAZlqI](https://github.com/rubima/magazine.rubyist.net/assets/69961886/83b7c2ad-d59a-469f-af65-77751261253a)
![GOAg9CxaYAAQ6Lm](https://github.com/rubima/magazine.rubyist.net/assets/69961886/318c6284-7dc0-485d-bdb1-0f3e1e32c8f7)
![GOAeuqYbAAANUrx](https://github.com/rubima/magazine.rubyist.net/assets/69961886/77b159d1-0069-4256-809d-b2e411c4a530)

撮影した人: ヤノ | ROUTE06  @ynndino88
何日目か:  Day3
ひとこと: 私もIVRyさんで黒電話になりました
https://github.com/rubima/magazine.rubyist.net/assets/69961886/29c0ea79-a17f-4a41-83d3-70a0222f5b1c
https://github.com/rubima/magazine.rubyist.net/assets/69961886/f3882dc1-7354-4388-b181-9d0f90f8066d

撮影した人: ヤノ | ROUTE06  @ynndino88
何日目か:  Day3
ひとこと: 最終日に見つけた顔はめパネル
![GOAg9EMaYAAte0g](https://github.com/rubima/magazine.rubyist.net/assets/69961886/a769b543-69c1-4e3c-b12d-2a6102b48fa0)

撮影した人: ヤノ | ROUTE06  @ynndino88
何日目か:  会期後
ひとこと: スタンプラリーをエクストラまで完走するとこうなる
![GOAsnsoaUAAOu-t](https://github.com/rubima/magazine.rubyist.net/assets/69961886/1f2b2f95-d0bd-4b0c-a071-b7edc6ffd938)

**Comment by okuramasafumi** [comment]
撮影者： @okuramasafumi （大倉雅史）

何日目か：1日目っぽい
ひとこと：RBSに興味がある人たち

![IMG_1348](https://github.com/rubima/magazine.rubyist.net/assets/1012014/3b078137-f1b7-4894-93c6-73a34abf7715)

何日目か：3日目
ひとこと：バイリンガル沖縄そば

![IMG_1351](https://github.com/rubima/magazine.rubyist.net/assets/1012014/5061b665-e032-4527-8a23-ed2ad13e0218)

何日目か：3日目
ひとこと：Palkanが書いた本に自作gemが載っていたので記念

![IMG_1352](https://github.com/rubima/magazine.rubyist.net/assets/1012014/846f2c77-cc37-4011-939f-4cd924fe6751)

何日目か：3日目（アフターパーティー）
ひとこと：コミッター達＋しおいさん

![IMG_1359](https://github.com/rubima/magazine.rubyist.net/assets/1012014/931620c5-82eb-4b37-968a-7c324c77b5f9)

何日目か：4日目
ひとこと：RubyKaigiが終われない

![IMG_1381](https://github.com/rubima/magazine.rubyist.net/assets/1012014/a7ea3788-031a-4817-9343-5eab3761e9ca)

何日目か：6日目
ひとこと：Rubyists on a Ship

![IMG_1464](https://github.com/rubima/magazine.rubyist.net/assets/1012014/f6e8c388-f5ce-4e0a-97d7-90fda103782b)

**Comment by hasumikin** [comment]
撮影した人: hasumikin
何日目か:  Day3
ひとこと: このお三方とランチのステーキを食べに行きました。彼らがどうみても太陽戦隊サンバルカンだったので、これを撮影しました。ただ、緑のスタッフかりゆしを着た松田さんとピンクのSTORES Tシャツを着た笹田さんも連れてきて秘密戦隊ゴレンジャーにするべきだったと反省しています

https://x.com/hasumikin/status/1791328343809462713

**Comment by aoirolamp** [comment]
撮影した人: おおき（aoirolamp）
何日目か:  Day2
ひとこと: RubyFriends

![20240516_200834](https://github.com/rubima/magazine.rubyist.net/assets/19222647/cbf021ed-3d8c-47a2-8c50-878d70cac209)

**Comment by hsbt** [comment]
撮影した人: hsbt

* RubyFriendsな写真

![IMG_0135](https://github.com/rubima/magazine.rubyist.net/assets/12301/d349efe5-09d5-4309-939a-f6654511b18f)

* 例えば突発的に発生した議論の様子や、偶然な一瞬を捉えた写真

![IMG_0064](https://github.com/rubima/magazine.rubyist.net/assets/12301/e071030c-51b3-4551-b6ee-25390d8f2e78)

* 一目でRubyKaigi 2024だなとわかるような特徴的な写真

![DSC05202](https://github.com/rubima/magazine.rubyist.net/assets/12301/d6de07b2-f036-4825-8b15-04145aa9dc52)

**Comment by asya81** [comment]
撮影した人: かわかみ(kota_syan)

何日目か:  Day0
ひとこと: プレチェックイン前の受付の皆さん
https://cdn-ak.f.st-hatena.com/images/fotolife/a/asya81jp/20240625/20240625203646.jpg

何日目か:  Day1 
ひとこと: 派手髪.rb
https://x.com/kota_syan/status/1790693066728485099

何日目か:  Day1 
ひとこと: RubyFriends@Official Party
https://x.com/kota_syan/status/1790693504861319651

何日目か:  Day2
ひとこと: NOCチームの皆さま
https://x.com/kota_syan/status/1792139596517798365

何日目か:  Day3
ひとこと: "おもしろうちわを持ちながら真面目な話をしているmameさんと、見守るk0kubunさん、そしてニヤニヤして聞いている金子さん"
https://cdn-ak.f.st-hatena.com/images/fotolife/a/asya81jp/20240618/20240618003837.jpg

何日目か:  Day3
ひとこと: and the World
https://cdn-ak.f.st-hatena.com/images/fotolife/a/asya81jp/20240618/20240618015346.jpg

何日目か:  Day3
ひとこと: hanachinさんとルーサーくん
https://x.com/kota_syan/status/1791485894572364009

何日目か:  Day3
ひとこと: RFF
https://x.com/kota_syan/status/1792165513650483622

**Comment by katoangelchiho** [comment]
撮影した人：えんじぇる

-  託児サポートの一貫で美ら海水族館アクティビティに行く時のバス
![_DSC9695](https://github.com/rubima/magazine.rubyist.net/assets/45547815/e188384d-3e57-47b7-8bb5-d7ed9190f6ff)

-  美ら海水族館を楽しんでいる子どもたち（保護者に掲載許可を得ています）
![_DSC9730](https://github.com/rubima/magazine.rubyist.net/assets/45547815/3e6a6467-23e6-4436-ab2b-f3e80b502169)

**Comment by neko314** [comment]
7月に入ってもしばらくopenにしていましたが、記事への転記も完了したので、closeします。
みなさん素敵なたくさんの写真のご提供ありがとうございました！
