### ISSUE TITLE
0064: 20周年なのでneko314がko1にインタビューする

### ISSUE THREAD

**Issue by kakutani** [rubima/magazine.rubyist.net#512]
> Hotlinks: 20周年なのでこの人、というインタビューをやる
いまるびまを頑張っている @neko314 が @ko1 にるびま20周年インタビューをする、というのはどうか!??!

OKいただきました(嬉)

_Originally posted by @neko314 in https://github.com/rubima/magazine.rubyist.net/discussions/494#discussioncomment-10063153_

実現させましょう!!

**Comment by kakutani** [comment]
@neko314 インタビューについて、 @takahashim からは「いいんじゃないですか」的な感じでした!
東京に来るタイミングはあるにはあるけど8月の終わりのほうのようなので、9月末リリースデッドラインの進行を考慮すると、8月前半あたりにインタビューを実施しておくのがよさそう…!

**Comment by neko314** [comment]
@kakutani 
ありがとうございます！
ではオンラインでやる方向で日程調整に入ります。

**Comment by kakutani** [comment]
@neko314 zoomは ruby-no-kai/official#405 で借りれないかなーと相談してみましたっ

**Comment by neko314** [comment]
@kakutani 
正式なお返事を漏らしていた。
Zoom、お借りしたいです！
